// frontend-react/pages/module/admin/view/tnb/tax-tnb-admin/view-admin/tax-tnb-view-admin.component.tsx
import {Button} from 'primereact/button';
import {Column} from 'primereact/column';
import {Dropdown} from 'primereact/dropdown';
import {TabView, TabPanel} from 'primereact/tabview';
import {DataTable} from 'primereact/datatable';
import {Dialog} from 'primereact/dialog';
import {InputNumber, InputNumberChangeEvent} from 'primereact/inputnumber';
import {InputText} from 'primereact/inputtext';
import {classNames} from 'primereact/utils';
import { InputTextarea } from 'primereact/inputtextarea';
import {AxiosResponse} from 'axios';
import React, {useEffect, useState} from 'react';
import {Calendar, CalendarChangeEvent} from 'primereact/calendar';
import { format } from 'date-fns';
import { InputSwitch } from "primereact/inputswitch";
import {MultiSelect} from "primereact/multiselect";
import  {TaxTnbDto}  from '/pages/controller/model/TaxTnb.model';

const View = ({visible,onClose,selectedItem}) => {

    const emptyItem = new TaxTnbDto();
    const [item, setItem] = useState<TaxTnbDto>(emptyItem);
    const [submitted, setSubmitted] = useState(false);
    const [activeIndex, setActiveIndex] = useState<number>(0);

    useEffect(() => {
        setItem(selectedItem ? { ...selectedItem } : { ...emptyItem });
    }, [selectedItem]);

    const onTabChange = (e: { index: number }) => {
        setActiveIndex(e.index);
    };

    const hideDialog = () => {
        setSubmitted(false);
        onClose();
    };

    const itemDialogFooter = ( <>
        <Button label="Cancel" icon="pi pi-times" text onClick={hideDialog} /> < />
    );

return(
<Dialog visible={visible} style={{width: '70vw'}} header="TaxTnb Details" modal className="p-fluid" footer={itemDialogFooter} onHide={hideDialog} >
<TabView activeIndex={activeIndex} onTabChange={onTabChange}>
<TabPanel header="TaxTnb">
    <div className="formgrid grid">

                <div className="field col-6">
                    <label htmlFor="annee">Annee</label>
                    <InputNumber id="annee" value={item.annee} disabled/>
                </div>

                <div className="field col-6">
                    <label htmlFor="montantBase">MontantBase</label>
                    <InputNumber id="montantBase" value={item.montantBase} disabled/>
                </div>

                <div className="field col-6">
                    <label htmlFor="mantantRetard">MantantRetard</label>
                    <InputNumber id="mantantRetard" value={item.mantantRetard} disabled/>
                </div>

                <div className="field col-6">
                    <label htmlFor="nombreMoisRetard">NombreMoisRetard</label>
                    <InputNumber id="nombreMoisRetard" value={item.nombreMoisRetard} disabled/>
                </div>

                <div className="field col-6">
                    <label htmlFor="montantTotal">MontantTotal</label>
                    <InputNumber id="montantTotal" value={item.montantTotal} disabled/>
                </div>

        <div className="field col-6">
            <label htmlFor="datePresentation">DatePresentation</label>
            <Calendar id="datePresentation" value={selectedItem?.datePresentation} disabled dateFormat="dd/mm/yy" showTime />
        </div>

        <div className="field col-6">
            <label htmlFor="dateTaxeTnb">DateTaxeTnb</label>
            <Calendar id="dateTaxeTnb" value={selectedItem?.dateTaxeTnb} disabled dateFormat="dd/mm/yy" showTime />
        </div>

                <div className="field col-6">
                    <label htmlFor="redevable">Redevable</label>
                    <Dropdown  id="redevableDropdown"  value={selectedItem?.redevable?.cin}  disabled  />
                </div>
                <div className="field col-6">
                    <label htmlFor="terrain">Terrain</label>
                    <Dropdown  id="terrainDropdown"  value={selectedItem?.terrain?.ref}  disabled  />
                </div>
                <div className="field col-6">
                    <label htmlFor="tauxTaxTnb">TauxTaxTnb</label>
                    <Dropdown  id="tauxTaxTnbDropdown"  value={selectedItem?.tauxTaxTnb?.id}  disabled  />
                </div>
        </div>
</TabPanel>
</TabView>
</Dialog>
);
};
export default View;

// frontend-ang/src/app/module/admin/view/tnb/tax-tnb-admin/view-admin/tax-tnb-view-admin.component.ts
import {Component, OnInit} from '@angular/core';


import {AbstractViewController} from 'src/app/zynerator/controller/AbstractViewController';
import { environment } from 'src/environments/environment';

import {TaxTnbService} from 'src/app/controller/service/TaxTnb.service';
import {TaxTnbDto} from 'src/app/controller/model/TaxTnb.model';
import {TaxTnbCriteria} from 'src/app/controller/criteria/TaxTnbCriteria.model';

import {RedevableDto} from 'src/app/controller/model/Redevable.model';
import {RedevableService} from 'src/app/controller/service/Redevable.service';
import {TauxTaxTnbDto} from 'src/app/controller/model/TauxTaxTnb.model';
import {TauxTaxTnbService} from 'src/app/controller/service/TauxTaxTnb.service';
import {TerrainDto} from 'src/app/controller/model/Terrain.model';
import {TerrainService} from 'src/app/controller/service/Terrain.service';
@Component({
  selector: 'app-tax-tnb-view-admin',
  templateUrl: './tax-tnb-view-admin.component.html'
})
export class TaxTnbViewAdminComponent extends AbstractViewController<TaxTnbDto, TaxTnbCriteria, TaxTnbService> implements OnInit {


    constructor(private taxTnbService: TaxTnbService, private redevableService: RedevableService, private tauxTaxTnbService: TauxTaxTnbService, private terrainService: TerrainService){
        super(taxTnbService);
    }

    ngOnInit(): void {
        this.redevable = new RedevableDto();
        this.redevableService.findAll().subscribe((data) => this.redevables = data);
        this.terrain = new TerrainDto();
        this.terrainService.findAll().subscribe((data) => this.terrains = data);
        this.tauxTaxTnb = new TauxTaxTnbDto();
        this.tauxTaxTnbService.findAll().subscribe((data) => this.tauxTaxTnbs = data);
    }


    get redevable(): RedevableDto {
       return this.redevableService.item;
    }
    set redevable(value: RedevableDto) {
        this.redevableService.item = value;
    }
    get redevables():Array<RedevableDto> {
       return this.redevableService.items;
    }
    set redevables(value: Array<RedevableDto>) {
        this.redevableService.items = value;
    }
    get terrain(): TerrainDto {
       return this.terrainService.item;
    }
    set terrain(value: TerrainDto) {
        this.terrainService.item = value;
    }
    get terrains():Array<TerrainDto> {
       return this.terrainService.items;
    }
    set terrains(value: Array<TerrainDto>) {
        this.terrainService.items = value;
    }
    get tauxTaxTnb(): TauxTaxTnbDto {
       return this.tauxTaxTnbService.item;
    }
    set tauxTaxTnb(value: TauxTaxTnbDto) {
        this.tauxTaxTnbService.item = value;
    }
    get tauxTaxTnbs():Array<TauxTaxTnbDto> {
       return this.tauxTaxTnbService.items;
    }
    set tauxTaxTnbs(value: Array<TauxTaxTnbDto>) {
        this.tauxTaxTnbService.items = value;
    }


}


<p-dialog [(visible)]="viewDialog" [style]="{width: '70vw'}" header="{{'taxTnbTabPan' | translate}}" [modal]="true" styleClass="p-fluid">
    <ng-template pTemplate="content">
        <p-tabView>
            <p-tabPanel header="{{'taxTnbTabPan' | translate}}">
                <div class="grid">
                    <div class="field col-12 md:col-6">
                        <label for="1">{{'Annee' | translate}}</label>
                        <p-inputNumber class="mb-2 mr-2" id="1" [disabled]="true" placeholder="{{'Annee' | translate}}" [(ngModel)]="item.annee"></p-inputNumber>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="2">{{'Montant base' | translate}}</label>
                        <p-inputNumber class="mb-2 mr-2" id="2" [disabled]="true" placeholder="{{'Montant base' | translate}}" [(ngModel)]="item.montantBase"></p-inputNumber>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="3">{{'Mantant retard' | translate}}</label>
                        <p-inputNumber class="mb-2 mr-2" id="3" [disabled]="true" placeholder="{{'Mantant retard' | translate}}" [(ngModel)]="item.mantantRetard"></p-inputNumber>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="4">{{'Nombre mois retard' | translate}}</label>
                        <p-inputNumber class="mb-2 mr-2" id="4" [disabled]="true" placeholder="{{'Nombre mois retard' | translate}}" [(ngModel)]="item.nombreMoisRetard"></p-inputNumber>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="5">{{'Montant total' | translate}}</label>
                        <p-inputNumber class="mb-2 mr-2" id="5" [disabled]="true" placeholder="{{'Montant total' | translate}}" [(ngModel)]="item.montantTotal"></p-inputNumber>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="6">{{'Date presentation' | translate}}</label>
                        <p-calendar id="6" [disabled]="true"  [showTime]="true" [showSeconds]="false" placeholder="{{'Date presentation' | translate}}"  [(ngModel)]="item.datePresentation" dateFormat="{{dateFormat}}"></p-calendar>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="7">{{'Date taxe tnb' | translate}}</label>
                        <p-calendar id="7" [disabled]="true"  [showTime]="true" [showSeconds]="false" placeholder="{{'Date taxe tnb' | translate}}"  [(ngModel)]="item.dateTaxeTnb" dateFormat="{{dateFormat}}"></p-calendar>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="8">{{'Redevable' | translate}}</label>
                        <p-dropdown [options]="redevables" [(ngModel)]="item.redevable" id="8" [disabled]="true" optionLabel="cin" placeholder="{{'Redevable' | translate}}"></p-dropdown>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="9">{{'Terrain' | translate}}</label>
                        <p-dropdown [options]="terrains" [(ngModel)]="item.terrain" id="9" [disabled]="true" optionLabel="ref" placeholder="{{'Terrain' | translate}}"></p-dropdown>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="10">{{'Taux tax tnb' | translate}}</label>
                        <p-dropdown [options]="tauxTaxTnbs" [(ngModel)]="item.tauxTaxTnb" id="10" [disabled]="true" optionLabel="id" placeholder="{{'Taux tax tnb' | translate}}"></p-dropdown>
                    </div>
                </div>
            </p-tabPanel>

        </p-tabView>

    </ng-template>

    <ng-template pTemplate="footer" >
        <div class="grid-footer">
            <div>
                <button pButton pRipple label="Annuler" icon="pi pi-times" class="p-button-outlined" (click)="hideViewDialog()"></button>
            </div>
        </div>
    </ng-template>
</p-dialog>
