// frontend-react/pages/module/admin/view/collaborateur/terrain-admin/create-admin/terrain-create-admin.component.tsx
import {Button} from 'primereact/button';
import {Column} from 'primereact/column';
import {Dropdown} from 'primereact/dropdown';
import {TabView, TabPanel} from 'primereact/tabview';
import {DataTable} from 'primereact/datatable';
import {Dialog} from 'primereact/dialog';
import {InputNumber, InputNumberChangeEvent} from 'primereact/inputnumber';
import {InputText} from 'primereact/inputtext';
import {classNames} from 'primereact/utils';
import { InputTextarea } from 'primereact/inputtextarea';
import {AxiosResponse} from 'axios';
import React, {useEffect, useState} from 'react';
import {Calendar, CalendarChangeEvent} from 'primereact/calendar';
import { format } from 'date-fns';
import {InputNumberChangeEvent} from 'primereact/inputnumber';
import { InputSwitch } from "primereact/inputswitch";
import {MultiSelect} from "primereact/multiselect";
import {MessageService} from "/pages/controller/service/MessageService";
import {TerrainService} from '/pages/controller/service/Terrain.service';
import  {TerrainDto}  from '/pages/controller/model/Terrain.model';
import {CategorieTerrainDto} from '/pages/controller/model/CategorieTerrain.model';
import {CategorieTerrainService} from '/pages/controller/service/CategorieTerrain.service';
import {RedevableDto} from '/pages/controller/model/Redevable.model';
import {RedevableService} from '/pages/controller/service/Redevable.service';
const Create = ({visible, onClose, add, showToast, list}) => {

    const emptyItem = new TerrainDto();
    const [items, setItems] = useState<TerrainDto[]>([list]);
    const [item, setItem] = useState<TerrainDto>(emptyItem);
    const [submitted, setSubmitted] = useState(false);
    const [activeIndex, setActiveIndex] = useState<number>(0);
    const [activeTab, setActiveTab] = useState(0);

    const [redevables, setRedevables] = useState<RedevableDto[]>([]);
    const [categorieTerrains, setCategorieTerrains] = useState<CategorieTerrainDto[]>([]);

    type CategorieTerrainResponse = AxiosResponse<CategorieTerrainDto[]>;
    type RedevableResponse = AxiosResponse<RedevableDto[]>;


    useEffect(() => {
        const fetchData = async () => {
            try {
                const [redevablesResponse ,categorieTerrainsResponse ] = await Promise.all<RedevableResponse,CategorieTerrainResponse>([
                    RedevableService.getList(),
                    CategorieTerrainService.getList(),
                ]);
                setRedevables(redevablesResponse.data);
                setCategorieTerrains(categorieTerrainsResponse.data);
            } catch (error) {
                console.error(error);
            }
        };
        fetchData();
    }, []);

    const onDropdownChange = (e, field) => {
        setItem((prevState) => ({ ...prevState, [field]: e.value}));
    };


    const onTabChange = (e: { index: number }) => { setActiveIndex(e.index); };

    const hideDialog = () => {
        setSubmitted(false);
        onClose();
    };

    const saveItem = async () => {
        setSubmitted(true);
        let _items = [...items];
        let _item = {...item};
        if (!_item.id) {
            const response = await TerrainService.save(_item);
			_item.id = response.data.id;
            _items.push(_item);
            add(_item);
            MessageService.showToast(showToast, { severity: 'success', summary: 'Successful', detail: 'Terrain Created', life: 3000 });
        }
        setItems(_items);
        onClose();
        setItem(emptyItem);
    };

    const onInputTextChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>, name: string) => {
        const val = (e.target && e.target.value) || '';
        let _item = {...item};
        _item[`${name}`] = val;
        setItem(_item);
    };

    const onInputDateChange = (e: CalendarChangeEvent, name: string) => {
        const val = e.value || '';
        let _item = { ...item};
        _item[`${name}`] = val;
        setItem(_item);
    };

    const onInputNumerChange = (e: InputNumberChangeEvent, name: string) => {
        const val = e.value === null ? null : +e.value;
        setItem((prevItem) => ({ ...prevItem, [name]: val, }));
    };

    const onMultiSelectChange = (e, field) => {
      if (e && e.value && Array.isArray(e.value)) {
         const selectedValues = e.value.map(option => option && option.value);
         setItem(prevState => ({ ...prevState, [field]: selectedValues, }));
      }
    };

    const onBooleanInputChange = (e: any, name: string) => {
       const val = e.value;
       setItem((prevItem) => ({ ...prevItem, [name]: val, }));
    };

    const itemDialogFooter = ( <>
        <Button label="Cancel" icon="pi pi-times" text onClick={hideDialog} />
        <Button label="Save" icon="pi pi-check" text onClick={saveItem} /> < />
    );

return(
    <Dialog visible={visible} style={{width: '70vw'}} header="Terrain" modal className="p-fluid" footer={itemDialogFooter} onHide={hideDialog} >
        <TabView activeIndex={activeIndex} onTabChange={onTabChange}>
            <TabPanel header="Terrain">
                <div className="formgrid grid">
                    <div className="field col-6">
                    <label htmlFor="ref">Ref</label>
                    <InputText id="ref" value={item.ref} onChange={(e) => onInputTextChange(e, 'ref')} required autoFocus className={classNames({'p-invalid': submitted && !item.ref})} />
                    {submitted && !item.ref && <small className="p-invalid">Ref is required.</small>}
                    </div>
                    <div className="field col-6">
                    <label htmlFor="categorieTerrain">CategorieTerrain</label>
                    <Dropdown  id="categorieTerrainDropdown"  value={item.categorieTerrain} options={categorieTerrains} onChange={(e) => onDropdownChange(e, 'categorieTerrain')}   placeholder="Sélectionnez un categorieTerrain" filter filterPlaceholder="Rechercher un categorieTerrain" optionLabel="libelle" />
                    </div>
                    <div className="field col-6">
                    <label htmlFor="redevable">Redevable</label>
                    <Dropdown  id="redevableDropdown"  value={item.redevable} options={redevables} onChange={(e) => onDropdownChange(e, 'redevable')}   placeholder="Sélectionnez un redevable" filter filterPlaceholder="Rechercher un redevable" optionLabel="cin" />
                    </div>
                </div>
            </TabPanel>
        </TabView>
    </Dialog>
);
};
export default Create;

// frontend-ang/src/app/module/admin/view/collaborateur/terrain-admin/create-admin/terrain-create-admin.component.ts
import {Component, OnInit, Input} from '@angular/core';

import { AbstractCreateController } from 'src/app/zynerator/controller/AbstractCreateController';

import {TerrainService} from 'src/app/controller/service/Terrain.service';
import {TerrainDto} from 'src/app/controller/model/Terrain.model';
import {TerrainCriteria} from 'src/app/controller/criteria/TerrainCriteria.model';
import {RedevableDto} from 'src/app/controller/model/Redevable.model';
import {RedevableService} from 'src/app/controller/service/Redevable.service';
import {CategorieTerrainDto} from 'src/app/controller/model/CategorieTerrain.model';
import {CategorieTerrainService} from 'src/app/controller/service/CategorieTerrain.service';
@Component({
  selector: 'app-terrain-create-admin',
  templateUrl: './terrain-create-admin.component.html'
})
export class TerrainCreateAdminComponent extends AbstractCreateController<TerrainDto, TerrainCriteria, TerrainService>  implements OnInit {



   private _validTerrainRef = true;
    private _validCategorieTerrainCode = true;
    private _validCategorieTerrainLibelle = true;
    private _validRedevableCin = true;

    constructor( private terrainService: TerrainService , private redevableService: RedevableService, private categorieTerrainService: CategorieTerrainService) {
        super(terrainService);
    }

    ngOnInit(): void {
    this.categorieTerrain = new CategorieTerrainDto();
    this.categorieTerrainService.findAll().subscribe((data) => this.categorieTerrains = data);
    this.redevable = new RedevableDto();
    this.redevableService.findAll().subscribe((data) => this.redevables = data);
}





    public setValidation(value: boolean){
        this.validTerrainRef = value;
    }



    public validateForm(): void{
        this.errorMessages = new Array<string>();
        this.validateTerrainRef();
    }

    public validateTerrainRef(){
        if (this.stringUtilService.isEmpty(this.item.ref)) {
        this.errorMessages.push('Ref non valide');
        this.validTerrainRef = false;
        } else {
            this.validTerrainRef = true;
        }
    }


    public async openCreateRedevable(redevable: string) {
    const isPermistted = await this.roleService.isPermitted('Redevable', 'add');
    if(isPermistted) {
         this.redevable = new RedevableDto();
         this.createRedevableDialog = true;
    }else{
        this.messageService.add({
        severity: 'error', summary: 'erreur', detail: 'problème de permission'
        });
     }
    }

    get redevable(): RedevableDto {
        return this.redevableService.item;
    }
    set redevable(value: RedevableDto) {
        this.redevableService.item = value;
    }
    get redevables(): Array<RedevableDto> {
        return this.redevableService.items;
    }
    set redevables(value: Array<RedevableDto>) {
        this.redevableService.items = value;
    }
    get createRedevableDialog(): boolean {
       return this.redevableService.createDialog;
    }
    set createRedevableDialog(value: boolean) {
        this.redevableService.createDialog= value;
    }
    get categorieTerrain(): CategorieTerrainDto {
        return this.categorieTerrainService.item;
    }
    set categorieTerrain(value: CategorieTerrainDto) {
        this.categorieTerrainService.item = value;
    }
    get categorieTerrains(): Array<CategorieTerrainDto> {
        return this.categorieTerrainService.items;
    }
    set categorieTerrains(value: Array<CategorieTerrainDto>) {
        this.categorieTerrainService.items = value;
    }
    get createCategorieTerrainDialog(): boolean {
       return this.categorieTerrainService.createDialog;
    }
    set createCategorieTerrainDialog(value: boolean) {
        this.categorieTerrainService.createDialog= value;
    }



    get validTerrainRef(): boolean {
        return this._validTerrainRef;
    }

    set validTerrainRef(value: boolean) {
         this._validTerrainRef = value;
    }

    get validCategorieTerrainCode(): boolean {
        return this._validCategorieTerrainCode;
    }
    set validCategorieTerrainCode(value: boolean) {
        this._validCategorieTerrainCode = value;
    }
    get validCategorieTerrainLibelle(): boolean {
        return this._validCategorieTerrainLibelle;
    }
    set validCategorieTerrainLibelle(value: boolean) {
        this._validCategorieTerrainLibelle = value;
    }
    get validRedevableCin(): boolean {
        return this._validRedevableCin;
    }
    set validRedevableCin(value: boolean) {
        this._validRedevableCin = value;
    }


}

        <p-dialog [(visible)]="createDialog" [style]="{width: '70vw'}" header="{{'terrainTabPan' | translate}}" [modal]="true" styleClass="p-fluid" [maximizable]="true" [draggable]="false" [resizable]="false">
            <ng-template pTemplate="content" >
                        <p-tabView>
                            <p-tabPanel header="{{'terrainTabPan' | translate}}">
                                <div class="grid">

                                                <div class="field col-12 md:col-6">
                                                    <label for="1">{{'terrainRef' | translate}}<span style="color: red;">*</span></label>
                                                    <input class="mb-2 mr-2" type="text" pInputText  placeholder="{{'terrainRef' | translate}}" id="1" [(ngModel)]="item.ref"
                                                            [ngClass]="{'ng-invalid ng-dirty' : !validTerrainRef}"  />
                                                    <small class='p-error' *ngIf='!validTerrainRef'>Ref est obligatoire.</small>
                                                </div>



                                            <div class="field col-11 md:col-6">
                                                <label for="2">{{'terrainCategorieTerrain' | translate}}</label>
                                                <p-dropdown  appendTo="body"  [options]="categorieTerrains" [(ngModel)]="item.categorieTerrain" id="2" [filter]="true" filterMatchMode="contains"
                                                        [showClear]="true" optionLabel="libelle" placeholder="{{'terrainCategorieTerrain' | translate}}"  >
                                                </p-dropdown>
                                                
                                            </div>
                                            <div class="field col-11 md:col-5">
                                                <label for="3">{{'terrainRedevable' | translate}}</label>
                                                <p-dropdown  appendTo="body"  [options]="redevables" [(ngModel)]="item.redevable" id="3" [filter]="true" filterMatchMode="contains"
                                                        [showClear]="true" optionLabel="cin" placeholder="{{'terrainRedevable' | translate}}"  >
                                                </p-dropdown>
                                                
                                            </div>
                                                <div class="col-1">
                                                    <label></label>
                                                    <button pButton pRipple type="button" icon="pi pi-plus" (click)="openCreateRedevable('Redevable')" class="p-button-success one-colonne-btn-success-align"></button>
                                                </div>
                                </div>
                            </p-tabPanel>

                        </p-tabView>

            </ng-template>

            <ng-template pTemplate="footer" >
                <div class="grid-step">
                        <div style="margin-left: auto;">
                            <button pButton pRipple  label="{{'validate' | translate}}"  icon="pi pi-check" style="margin:10px" (click)="save()"></button>
                        </div>
                        <div>
                            <button pButton pRipple  label="{{'cancel' | translate}}" icon="pi pi-times" class="p-button-outlined" (click)="hideCreateDialog()"></button>
                        </div>

                </div>
            </ng-template>

            <app-redevable-create-admin></app-redevable-create-admin>


    </p-dialog>
