// frontend-ang/src/app/module/admin/view/tnb/tax-tnb-admin/edit-admin/tax-tnb-edit-admin.component.ts
import {Component, OnInit, Input} from '@angular/core';


import {AbstractEditController} from 'src/app/zynerator/controller/AbstractEditController';

import {TaxTnbService} from 'src/app/controller/service/TaxTnb.service';
import {TaxTnbDto} from 'src/app/controller/model/TaxTnb.model';
import {TaxTnbCriteria} from 'src/app/controller/criteria/TaxTnbCriteria.model';


import {RedevableDto} from 'src/app/controller/model/Redevable.model';
import {RedevableService} from 'src/app/controller/service/Redevable.service';
import {TauxTaxTnbDto} from 'src/app/controller/model/TauxTaxTnb.model';
import {TauxTaxTnbService} from 'src/app/controller/service/TauxTaxTnb.service';
import {TerrainDto} from 'src/app/controller/model/Terrain.model';
import {TerrainService} from 'src/app/controller/service/Terrain.service';

@Component({
  selector: 'app-tax-tnb-edit-admin',
  templateUrl: './tax-tnb-edit-admin.component.html'
})
export class TaxTnbEditAdminComponent extends AbstractEditController<TaxTnbDto, TaxTnbCriteria, TaxTnbService>   implements OnInit {



    private _validRedevableCin = true;
    private _validTerrainRef = true;



    constructor( private taxTnbService: TaxTnbService , private redevableService: RedevableService, private tauxTaxTnbService: TauxTaxTnbService, private terrainService: TerrainService) {
        super(taxTnbService);
    }

    ngOnInit(): void {
    this.redevable = new RedevableDto();
    this.redevableService.findAll().subscribe((data) => this.redevables = data);
    this.terrain = new TerrainDto();
    this.terrainService.findAll().subscribe((data) => this.terrains = data);
    this.tauxTaxTnb = new TauxTaxTnbDto();
    this.tauxTaxTnbService.findAll().subscribe((data) => this.tauxTaxTnbs = data);
}
    public prepareEdit() {
        this.item.datePresentation = this.taxTnbService.format(this.item.datePresentation);
        this.item.dateTaxeTnb = this.taxTnbService.format(this.item.dateTaxeTnb);
    }



    public setValidation(value : boolean){
        }
    public validateForm(): void{
        this.errorMessages = new Array<string>();
    }




   get redevable(): RedevableDto {
       return this.redevableService.item;
   }
  set redevable(value: RedevableDto) {
        this.redevableService.item = value;
   }
   get redevables(): Array<RedevableDto> {
        return this.redevableService.items;
   }
   set redevables(value: Array<RedevableDto>) {
        this.redevableService.items = value;
   }
   get createRedevableDialog(): boolean {
       return this.redevableService.createDialog;
   }
  set createRedevableDialog(value: boolean) {
       this.redevableService.createDialog= value;
   }
   get terrain(): TerrainDto {
       return this.terrainService.item;
   }
  set terrain(value: TerrainDto) {
        this.terrainService.item = value;
   }
   get terrains(): Array<TerrainDto> {
        return this.terrainService.items;
   }
   set terrains(value: Array<TerrainDto>) {
        this.terrainService.items = value;
   }
   get createTerrainDialog(): boolean {
       return this.terrainService.createDialog;
   }
  set createTerrainDialog(value: boolean) {
       this.terrainService.createDialog= value;
   }
   get tauxTaxTnb(): TauxTaxTnbDto {
       return this.tauxTaxTnbService.item;
   }
  set tauxTaxTnb(value: TauxTaxTnbDto) {
        this.tauxTaxTnbService.item = value;
   }
   get tauxTaxTnbs(): Array<TauxTaxTnbDto> {
        return this.tauxTaxTnbService.items;
   }
   set tauxTaxTnbs(value: Array<TauxTaxTnbDto>) {
        this.tauxTaxTnbService.items = value;
   }
   get createTauxTaxTnbDialog(): boolean {
       return this.tauxTaxTnbService.createDialog;
   }
  set createTauxTaxTnbDialog(value: boolean) {
       this.tauxTaxTnbService.createDialog= value;
   }



    get validRedevableCin(): boolean {
        return this._validRedevableCin;
    }
    set validRedevableCin(value: boolean) {
        this._validRedevableCin = value;
    }
    get validTerrainRef(): boolean {
        return this._validTerrainRef;
    }
    set validTerrainRef(value: boolean) {
        this._validTerrainRef = value;
    }
}

        <p-dialog [(visible)]="editDialog" [style]="{width: '70vw'}" header="{{'taxTnbTabPan' | translate}}" [modal]="true" styleClass="p-fluid" [maximizable]="true" [draggable]="false" [resizable]="false">
            <ng-template pTemplate="content" >
                <p-tabView>
                    <p-tabPanel header="{{'taxTnbTabPan' | translate}}">
                        <div class="grid">

                                        <div class="field col-12 md:col-6">
                                            <label for="1">{{'taxTnbAnnee' | translate}}</label>
                                            <p-inputNumber class="mb-2 mr-2" id="1" placeholder="{{'taxTnbAnnee' | translate}}" [(ngModel)]="item.annee"  >
                                            </p-inputNumber>
                                            
                                        </div>

                                        <div class="field col-12 md:col-6">
                                            <label for="2">{{'taxTnbMontantBase' | translate}}</label>
                                            <p-inputNumber class="mb-2 mr-2" id="2" placeholder="{{'taxTnbMontantBase' | translate}}" [(ngModel)]="item.montantBase"  >
                                            </p-inputNumber>
                                            
                                        </div>

                                        <div class="field col-12 md:col-6">
                                            <label for="3">{{'taxTnbMantantRetard' | translate}}</label>
                                            <p-inputNumber class="mb-2 mr-2" id="3" placeholder="{{'taxTnbMantantRetard' | translate}}" [(ngModel)]="item.mantantRetard"  >
                                            </p-inputNumber>
                                            
                                        </div>

                                        <div class="field col-12 md:col-6">
                                            <label for="4">{{'taxTnbNombreMoisRetard' | translate}}</label>
                                            <p-inputNumber class="mb-2 mr-2" id="4" placeholder="{{'taxTnbNombreMoisRetard' | translate}}" [(ngModel)]="item.nombreMoisRetard"  >
                                            </p-inputNumber>
                                            
                                        </div>

                                        <div class="field col-12 md:col-6">
                                            <label for="5">{{'taxTnbMontantTotal' | translate}}</label>
                                            <p-inputNumber class="mb-2 mr-2" id="5" placeholder="{{'taxTnbMontantTotal' | translate}}" [(ngModel)]="item.montantTotal"  >
                                            </p-inputNumber>
                                            
                                        </div>

                                        <div class="field col-12 md:col-6">
                                            <label for="6">{{'taxTnbDatePresentation' | translate}}</label>
                                            <p-calendar appendTo="body" id="6"  [showTime]="true" [showSeconds]="false" placeholder="{{'taxTnbDatePresentation' | translate}}"  [(ngModel)]="item.datePresentation"
                                                    dateFormat="{{dateFormat}}"  >
                                            </p-calendar>
                                            
                                        </div>

                                        <div class="field col-12 md:col-6">
                                            <label for="7">{{'taxTnbDateTaxeTnb' | translate}}</label>
                                            <p-calendar appendTo="body" id="7"  [showTime]="true" [showSeconds]="false" placeholder="{{'taxTnbDateTaxeTnb' | translate}}"  [(ngModel)]="item.dateTaxeTnb"
                                                    dateFormat="{{dateFormat}}"  >
                                            </p-calendar>
                                            
                                        </div>

                                    <div class="field col-11 md:col-6">
                                        <label for="8">{{'taxTnbRedevable' | translate}}</label>
                                        <p-dropdown  appendTo="body"  [options]="redevables" [(ngModel)]="item.redevable" id="8" [filter]="true" filterMatchMode="contains"
                                                [showClear]="true" optionLabel="cin" placeholder="{{'taxTnbRedevable' | translate}}"  >
                                        </p-dropdown>
                                        
                                    </div>
                                    <div class="field col-11 md:col-6">
                                        <label for="9">{{'taxTnbTerrain' | translate}}</label>
                                        <p-dropdown  appendTo="body"  [options]="terrains" [(ngModel)]="item.terrain" id="9" [filter]="true" filterMatchMode="contains"
                                                [showClear]="true" optionLabel="ref" placeholder="{{'taxTnbTerrain' | translate}}"  >
                                        </p-dropdown>
                                        
                                    </div>
                                    <div class="field col-11 md:col-6">
                                        <label for="10">{{'taxTnbTauxTaxTnb' | translate}}</label>
                                        <p-dropdown  appendTo="body"  [options]="tauxTaxTnbs" [(ngModel)]="item.tauxTaxTnb" id="10" [filter]="true" filterMatchMode="contains"
                                                [showClear]="true" optionLabel="id" placeholder="{{'taxTnbTauxTaxTnb' | translate}}"  >
                                        </p-dropdown>
                                        
                                    </div>
                        </div>
                    </p-tabPanel>

                </p-tabView>
            </ng-template>

            <ng-template pTemplate="footer" >
                <div class="grid-footer">
                        <div>
                            <button pButton pRipple label="Annuler" icon="pi pi-times" class="p-button-outlined" (click)="hideEditDialog()"></button>
                        </div>
                    <div>
                        <button pButton pRipple label="Valider" icon="pi pi-check" style="margin:10px" (click)="edit()"></button>
                    </div>
                </div>
            </ng-template>



    </p-dialog>

// frontend-react/pages/module/admin/view/tnb/tax-tnb-admin/edit-admin/tax-tnb-edit-admin.component.tsx
import {Button} from 'primereact/button';
import {Column} from 'primereact/column';
import {Dropdown} from 'primereact/dropdown';
import {TabView, TabPanel} from 'primereact/tabview';
import {DataTable} from 'primereact/datatable';
import {Dialog} from 'primereact/dialog';
import {InputNumber, InputNumberChangeEvent} from 'primereact/inputnumber';
import {InputText} from 'primereact/inputtext';
import {classNames} from 'primereact/utils';
import { InputTextarea } from 'primereact/inputtextarea';
import {AxiosResponse} from 'axios';
import React, {useEffect, useState} from 'react';
import {Calendar, CalendarChangeEvent} from 'primereact/calendar';
import { format } from 'date-fns';
import {InputNumberChangeEvent} from 'primereact/inputnumber';
import { InputSwitch } from "primereact/inputswitch";
import {MultiSelect} from "primereact/multiselect";import {MessageService} from "/pages/controller/service/MessageService";

import {TaxTnbService} from '/pages/controller/service/TaxTnb.service';
import  {TaxTnbDto}  from '/pages/controller/model/TaxTnb.model';

import {TerrainDto} from '/pages/controller/model/Terrain.model';
import {TerrainService} from '/pages/controller/service/Terrain.service';
import {RedevableDto} from '/pages/controller/model/Redevable.model';
import {RedevableService} from '/pages/controller/service/Redevable.service';
import {TauxTaxTnbDto} from '/pages/controller/model/TauxTaxTnb.model';
import {TauxTaxTnbService} from '/pages/controller/service/TauxTaxTnb.service';
const Edit = ({visible, onClose, showToast, selectedItem, update}) => {

    const emptyItem = new TaxTnbDto();
    const [submitted, setSubmitted] = useState(false);
    const [activeIndex, setActiveIndex] = useState<number>(0);
    const [activeTab, setActiveTab] = useState(0);
    const [item, setItem] = useState<TaxTnbDto>( emptyItem);
    const [redevables, setRedevables] = useState<RedevableDto[]>([]);
    const [terrains, setTerrains] = useState<TerrainDto[]>([]);
    const [tauxTaxTnbs, setTauxTaxTnbs] = useState<TauxTaxTnbDto[]>([]);

    type TerrainResponse = AxiosResponse<TerrainDto[]>;
    type RedevableResponse = AxiosResponse<RedevableDto[]>;
    type TauxTaxTnbResponse = AxiosResponse<TauxTaxTnbDto[]>;


    useEffect(() => {
        const fetchData = async () => {
            try {
                const [redevablesResponse ,terrainsResponse ,tauxTaxTnbsResponse ] = await Promise.all<RedevableResponse,TerrainResponse,TauxTaxTnbResponse>([
                    RedevableService.getList(),
                    TerrainService.getList(),
                    TauxTaxTnbService.getList(),
                ]);
                setRedevables(redevablesResponse.data);
                setTerrains(terrainsResponse.data);
                setTauxTaxTnbs(tauxTaxTnbsResponse.data);
            } catch (error) {
                console.error(error);
            }
        };
    fetchData();
    setItem(selectedItem ? { ...selectedItem } : { ...emptyItem });
    }, [selectedItem]);



    const onDropdownChange = (e, field) => {
        setItem((prevState) => ({ ...prevState, [field]: e.value, }));
    };


    const onTabChange = (e: { index: number }) => {
        setActiveIndex(e.index);
    };

    const hideDialog = () => {
        setSubmitted(false);
        onClose();
    };

    const saveItem = async () => {
        setSubmitted(true);
        let _item = {...item};
        try {
            if (_item.id) {
                await TaxTnbService.update(_item).then((response) => {
                    console.log(response.data);
                    update(response.data);
                    onClose();
                });
                MessageService.showToast(showToast, { severity: 'success', summary: 'Successful', detail: 'TaxTnb Updated', life: 3000 });
            }
        } catch (error) {
            console.log(error);
            MessageService.showToast(showToast, { severity: 'Error', summary: 'Error', detail: 'Failed to save taxTnb', life: 3000 });
        }
    };

    const onInputTextChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>, name: string) => {
        const val = (e.target && e.target.value) || '';
        let _item = {...item};
        _item[`${name}`] = val;
        setItem(_item);
    };

    const onInputDateChange = (e: CalendarChangeEvent, name: string) => {
        const val = e.value || ''; // Utilisez e.value au lieu de e.target.value
        let _item = { ...item};
        _item[`${name}`] = val;
        setItem(_item);
    };

    const onInputNumerChange = (e: InputNumberChangeEvent, name: string) => {
        const val = e.value === null ? null : +e.value;
        setItem((prevItem) => ({ ...prevItem, [name]: val, }));
    };

    const onMultiSelectChange = (e, field) => {
        if (e && e.value && Array.isArray(e.value)) {
            const selectedValues = e.value.map(option => option && option.value);
            setItem(prevState => ({ ...prevState, [field]: selectedValues, }));
        }
    };

    const onBooleanInputChange = (e: any, name: string) => {
        const val = e.value;
        setItem((prevItem) => ({ ...prevItem, [name]: val, }));
    };

    const itemDialogFooter = ( <>
        <Button label="Cancel" icon="pi pi-times" text onClick={hideDialog} />
        <Button label="Save" icon="pi pi-check" text onClick={saveItem} /> < />
    );

return(
    <Dialog visible={visible} style={{width: '70vw'}} header="TaxTnb" modal className="p-fluid" footer={itemDialogFooter} onHide={hideDialog}>
        <TabView activeIndex={activeIndex} onTabChange={onTabChange}>
            <TabPanel header="TaxTnb">
                <div className="formgrid grid">
                    <div className="field col-6">
                        <label htmlFor="annee">Annee</label>
                        <InputNumber id="annee" value={item ? item.annee : 0} onChange={(e) => onInputNumerChange(e, 'annee')}/>
                    </div>
                    <div className="field col-6">
                        <label htmlFor="montantBase">MontantBase</label>
                        <InputNumber id="montantBase" value={item ? item.montantBase : 0} onChange={(e) => onInputNumerChange(e, 'montantBase')}/>
                    </div>
                    <div className="field col-6">
                        <label htmlFor="mantantRetard">MantantRetard</label>
                        <InputNumber id="mantantRetard" value={item ? item.mantantRetard : 0} onChange={(e) => onInputNumerChange(e, 'mantantRetard')}/>
                    </div>
                    <div className="field col-6">
                        <label htmlFor="nombreMoisRetard">NombreMoisRetard</label>
                        <InputNumber id="nombreMoisRetard" value={item ? item.nombreMoisRetard : 0} onChange={(e) => onInputNumerChange(e, 'nombreMoisRetard')}/>
                    </div>
                    <div className="field col-6">
                        <label htmlFor="montantTotal">MontantTotal</label>
                        <InputNumber id="montantTotal" value={item ? item.montantTotal : 0} onChange={(e) => onInputNumerChange(e, 'montantTotal')}/>
                    </div>
                    <div className="field col-6">
                        <label htmlFor="datePresentation">DatePresentation</label>
                        <Calendar id="datePresentation" value={item ? item.datePresentation : ''} onChange={(e) => onInputDateChange(e, 'datePresentation')} dateFormat="dd/mm/yy" showTime />
                    </div>
                    <div className="field col-6">
                        <label htmlFor="dateTaxeTnb">DateTaxeTnb</label>
                        <Calendar id="dateTaxeTnb" value={item ? item.dateTaxeTnb : ''} onChange={(e) => onInputDateChange(e, 'dateTaxeTnb')} dateFormat="dd/mm/yy" showTime />
                    </div>
                    <div className="field col-6">
                        <label htmlFor="redevable">Redevable</label>
                        <Dropdown  id="redevableDropdown"  value={item ? item.redevable : ''} options={redevables} onChange={(e) => onDropdownChange(e, 'redevable')}   placeholder="Sélectionnez un redevable" filter filterPlaceholder="Rechercher un redevable" optionLabel="cin" />
                    </div>
                    <div className="field col-6">
                        <label htmlFor="terrain">Terrain</label>
                        <Dropdown  id="terrainDropdown"  value={item ? item.terrain : ''} options={terrains} onChange={(e) => onDropdownChange(e, 'terrain')}   placeholder="Sélectionnez un terrain" filter filterPlaceholder="Rechercher un terrain" optionLabel="ref" />
                    </div>
                    <div className="field col-6">
                        <label htmlFor="tauxTaxTnb">TauxTaxTnb</label>
                        <Dropdown  id="tauxTaxTnbDropdown"  value={item ? item.tauxTaxTnb : ''} options={tauxTaxTnbs} onChange={(e) => onDropdownChange(e, 'tauxTaxTnb')}   placeholder="Sélectionnez un tauxTaxTnb" filter filterPlaceholder="Rechercher un tauxTaxTnb" optionLabel="id" />
                    </div>
                </div>
            < /TabPanel>
        </TabView>
    </Dialog>
);
};
export default Edit;
