// frontend-ang/src/app/module/admin/view/collaborateur/redevable-admin/view-admin/redevable-view-admin.component.ts
import {Component, OnInit} from '@angular/core';


import {AbstractViewController} from 'src/app/zynerator/controller/AbstractViewController';
import { environment } from 'src/environments/environment';

import {RedevableService} from 'src/app/controller/service/Redevable.service';
import {RedevableDto} from 'src/app/controller/model/Redevable.model';
import {RedevableCriteria} from 'src/app/controller/criteria/RedevableCriteria.model';

@Component({
  selector: 'app-redevable-view-admin',
  templateUrl: './redevable-view-admin.component.html'
})
export class RedevableViewAdminComponent extends AbstractViewController<RedevableDto, RedevableCriteria, RedevableService> implements OnInit {


    constructor(private redevableService: RedevableService){
        super(redevableService);
    }

    ngOnInit(): void {
    }




}


<p-dialog [(visible)]="viewDialog" [style]="{width: '70vw'}" header="{{'redevableTabPan' | translate}}" [modal]="true" styleClass="p-fluid">
    <ng-template pTemplate="content">
        <p-tabView>
            <p-tabPanel header="{{'redevableTabPan' | translate}}">
                <div class="grid">
                    <div class="field col-12 md:col-6">
                        <label for="1">{{'Nom' | translate}}</label>
                        <input class="mb-2 mr-2" type="text" pInputText [disabled]="true" placeholder="{{'Nom' | translate}}" autofocus  id="1" [(ngModel)]="item.nom">
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="2">{{'Prenom' | translate}}</label>
                        <input class="mb-2 mr-2" type="text" pInputText [disabled]="true" placeholder="{{'Prenom' | translate}}" autofocus  id="2" [(ngModel)]="item.prenom">
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="3">{{'Cin' | translate}}</label>
                        <input class="mb-2 mr-2" type="text" pInputText [disabled]="true" placeholder="{{'Cin' | translate}}" autofocus  id="3" [(ngModel)]="item.cin">
                    </div>
                </div>
            </p-tabPanel>

        </p-tabView>

    </ng-template>

    <ng-template pTemplate="footer" >
        <div class="grid-footer">
            <div>
                <button pButton pRipple label="Annuler" icon="pi pi-times" class="p-button-outlined" (click)="hideViewDialog()"></button>
            </div>
        </div>
    </ng-template>
</p-dialog>

// frontend-react/pages/module/admin/view/collaborateur/redevable-admin/view-admin/redevable-view-admin.component.tsx
import {Button} from 'primereact/button';
import {Column} from 'primereact/column';
import {Dropdown} from 'primereact/dropdown';
import {TabView, TabPanel} from 'primereact/tabview';
import {DataTable} from 'primereact/datatable';
import {Dialog} from 'primereact/dialog';
import {InputNumber, InputNumberChangeEvent} from 'primereact/inputnumber';
import {InputText} from 'primereact/inputtext';
import {classNames} from 'primereact/utils';
import { InputTextarea } from 'primereact/inputtextarea';
import {AxiosResponse} from 'axios';
import React, {useEffect, useState} from 'react';
import {Calendar, CalendarChangeEvent} from 'primereact/calendar';
import { format } from 'date-fns';
import { InputSwitch } from "primereact/inputswitch";
import {MultiSelect} from "primereact/multiselect";
import  {RedevableDto}  from '/pages/controller/model/Redevable.model';

const View = ({visible,onClose,selectedItem}) => {

    const emptyItem = new RedevableDto();
    const [item, setItem] = useState<RedevableDto>(emptyItem);
    const [submitted, setSubmitted] = useState(false);
    const [activeIndex, setActiveIndex] = useState<number>(0);

    useEffect(() => {
        setItem(selectedItem ? { ...selectedItem } : { ...emptyItem });
    }, [selectedItem]);

    const onTabChange = (e: { index: number }) => {
        setActiveIndex(e.index);
    };

    const hideDialog = () => {
        setSubmitted(false);
        onClose();
    };

    const itemDialogFooter = ( <>
        <Button label="Cancel" icon="pi pi-times" text onClick={hideDialog} /> < />
    );

return(
<Dialog visible={visible} style={{width: '70vw'}} header="Redevable Details" modal className="p-fluid" footer={itemDialogFooter} onHide={hideDialog} >
<TabView activeIndex={activeIndex} onTabChange={onTabChange}>
<TabPanel header="Redevable">
    <div className="formgrid grid">

            <div className="field col-6">
                <label htmlFor="nom">Nom</label>
                <InputText id="nom" value={selectedItem?.nom} disabled   />
            </div>

            <div className="field col-6">
                <label htmlFor="prenom">Prenom</label>
                <InputText id="prenom" value={selectedItem?.prenom} disabled   />
            </div>

            <div className="field col-6">
                <label htmlFor="cin">Cin</label>
                <InputText id="cin" value={selectedItem?.cin} disabled   />
            </div>

        </div>
</TabPanel>
</TabView>
</Dialog>
);
};
export default View;
