// frontend-react/pages/module/admin/view/collaborateur/terrain-admin/list-admin/terrain-list-admin.component.tsx
import {Button} from 'primereact/button';
import {Column} from 'primereact/column';
import 'primereact/resources/themes/saga-blue/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import {DataTable} from 'primereact/datatable';
import {Dialog} from 'primereact/dialog';
import {FileUpload} from 'primereact/fileupload';
import {InputText} from 'primereact/inputtext';
import {Toast} from 'primereact/toast';
import {Toolbar} from 'primereact/toolbar';
import React, {useEffect, useRef, useState} from 'react';
import { Paginator } from 'primereact/paginator';
import {BaseCriteria} from '/pages/zynerator/criteria/BaseCriteria.model';
import {MessageService} from '/pages/controller/service/MessageService';
import {Card} from "primereact/card";
import {Calendar} from "primereact/calendar";
import {InputNumber} from "primereact/inputnumber";
import {Dropdown} from "primereact/dropdown";
import {AxiosResponse} from "axios";

import {TerrainService} from '/pages/controller/service/Terrain.service';
import {TerrainDto}  from '/pages/controller/model/Terrain.model';
import {TerrainCriteria} from "/pages/controller/criteria/TerrainCriteria.model";

import {CategorieTerrainDto} from '/pages/controller/model/CategorieTerrain.model';
import {CategorieTerrainService} from '/pages/controller/service/CategorieTerrain.service';
import {RedevableDto} from '/pages/controller/model/Redevable.model';
import {RedevableService} from '/pages/controller/service/Redevable.service';

import Edit from '/pages/module/admin/view/collaborateur/terrain-admin/edit-admin/terrain-edit-admin.component';
import Create from '/pages/module/admin/view/collaborateur/terrain-admin/create-admin/terrain-create-admin.component';
import View from '/pages/module/admin/view/collaborateur/terrain-admin/view-admin/terrain-view-admin.component';

const List = () => {

    const emptyItem = new TerrainDto();
    const [items, setItems] = useState<TerrainDto[]>([]);
    const [deleteItemDialog, setDeleteItemDialog] = useState(false);
    const [deleteItemsDialog, setDeleteItemsDialog] = useState(false);
    const [item, setItem] = useState<TerrainDto>(emptyItem);
    const [selectedItems, setSelectedItems] = useState<TerrainDto[]>([]);
    const [globalFilter, setGlobalFilter] = useState('');
    const [showCreateDialog, setShowCreateDialog] = useState<boolean>(false);
    const [showEditDialog, setShowEditDialog] = useState<boolean>(false);
    const [showViewDialog, setShowViewDialog] = useState<boolean>(false);
    const [selectedItem, setSelectedItem] = useState<TerrainDto | null>(null);
    const [rows, setRows] = useState<number>(10);
    const [totalRecords, setTotalRecords] = useState(0);
    const [criteria, setCriteria] = useState(new TerrainCriteria());
    const [first, setFirst] = useState(0);
    const toast = useRef<Toast>();
    const dt = useRef<DataTable<TerrainDto[]>>();
    const [findByCriteriaShow, setFindByCriteriaShow] = useState(false);
    const [isSearchTriggered, setIsSearchTriggered] = useState(false);

    const [categorieTerrains, setCategorieTerrains] = useState<CategorieTerrainDto[]>([]);
    type CategorieTerrainResponse = AxiosResponse<CategorieTerrainDto[]>;
    const [redevables, setRedevables] = useState<RedevableDto[]>([]);
    type RedevableResponse = AxiosResponse<RedevableDto[]>;

    const showSearch = () => { setFindByCriteriaShow(!findByCriteriaShow); };

    const handleValidateClick = () => {setIsSearchTriggered(true);};

    const handleCancelClick = () => {
        setCriteria(new TerrainCriteria());
        setIsSearchTriggered(true);
    };

    useEffect(() => {
        const fetchData = async () => {
            try {
                const [redevablesResponse ,categorieTerrainsResponse ] = await Promise.all<RedevableResponse,CategorieTerrainResponse>([
                    RedevableService.getList(),
                ]);
                setRedevables(redevablesResponse.data);
                setCategorieTerrains(categorieTerrainsResponse.data);
            } catch (error) {
                console.error(error);
            }
        };
        if (isSearchTriggered) {
            fetchItems(criteria);
            setIsSearchTriggered(false);
        }
        fetchData();
        fetchItems(criteria);
    }, [isSearchTriggered]);

    const fetchItems = async (criteria) => {
        try {
            const response = await TerrainService.findPaginatedByCriteria(criteria);
            const paginatedItems = response.data;
            setTotalRecords(paginatedItems.dataSize);
            setItems(paginatedItems.list);
        } catch (error) {
            console.log(error);
        }
    };

    const onPage = (event) => {
        const updatedCriteria = { ...criteria, page: event.page,maxResults: event.rows };
        setCriteria(updatedCriteria);
        setFirst(event.first);
        fetchItems(updatedCriteria);
    };

    const showCreateModal = (): void => {
        setShowCreateDialog(true);
    };

    const showEditModal = (item: TerrainDto) => {
        setSelectedItem(item);
        setShowEditDialog(true);
    };

    const showViewModal = (item: TerrainDto) => {
        setSelectedItem(item);
        setShowViewDialog(true);
    };

    const add = (item) => {
        setItems([...items, item]);
    };

    const update = (updatedItem: TerrainDto) => {
        const updatedList = items.map((item) => {
            if (item.id === updatedItem.id) { return updatedItem; }
            return item;
        });
        setItems(updatedList);
    };

   const hideDeleteItemDialog = () => {
        setDeleteItemDialog(false);
   };

   const hideDeleteItemsDialog = () => {
        setDeleteItemsDialog(false);
   };

    const confirmDeleteItem = (item: TerrainDto) => {
        setSelectedItem(item);
        setDeleteItemDialog(true);
    };

    const deleteItem = async () => {
        try{
            await TerrainService.delete(selectedItem?.id);
            setDeleteItemDialog(false);
            setItem(emptyItem);
            let _items = items.filter((val) => val.id !== selectedItem?.id);
            setItems(_items);
            MessageService.showToast(toast, { severity: 'success', summary: 'Successful', detail: 'Terrain Deleted', life: 3000 });
        } catch (error) {
            console.log(error);
        }
    };

    const exportCSV = () => {
        dt.current?.exportCSV();
    };

    const confirmDeleteSelected = () => {
        setDeleteItemsDialog(true);
    };

    const deleteSelectedItems = async () => {
        await TerrainService.deleteList(selectedItems);
        let _items = items.filter((val) => !selectedItems.includes(val));
        setItems(_items);
        setDeleteItemsDialog(false);
        setSelectedItems(null);
        MessageService.showToast(toast, { severity: 'success', summary: 'Successful', detail: 'Terrains Deleted', life: 3000 });
    };

   const leftToolbarTemplate = () => {
       return (
           <React.Fragment>
               <div className="my-2">
                   <Button label="New" icon="pi pi-plus" severity="success" className=" mr-2" onClick={ showCreateModal} />
                   <Button label="Delete" icon="pi pi-trash" severity="danger" className=" mr-2" onClick={confirmDeleteSelected} disabled={!selectedItems || !selectedItems.length} />
                   <Button label="Search" icon={`pi pi-${findByCriteriaShow ? 'angle-down' : 'angle-right'}`} className=" mr-2" severity="warning" onClick={showSearch} />
               </div>
           </React.Fragment>
       );
   };

   const rightToolbarTemplate = () => {
       return (
           <React.Fragment>
               <FileUpload mode="basic" accept="image/*" maxFileSize={1000000} chooseLabel="Import" className="mr-2 inline-block" />
               <Button label="Export" icon="pi pi-upload" severity="help" onClick={exportCSV} />
           </React.Fragment>
       );
   };

    const actionBodyTemplate = (rowData: TerrainDto) => {
       return ( <>
           <Button icon="pi pi-pencil" rounded severity="success" className="mr-1" onClick={() => showEditModal(rowData)} />
           <Button icon="pi pi-trash" rounded  severity="danger" className="mr-1"  onClick={() => confirmDeleteItem(rowData)} />
           <Button icon="pi pi-eye" rounded severity="info" className="mr-1" onClick={() => showViewModal(rowData)} /> < />
       );
    };

    const header = (
        <div className="flex flex-column md:flex-row md:justify-content-between md:align-items-center">
        <h5 className="m-0">Manage terrains</h5>
        <span className="block mt-2 md:mt-0 p-input-icon-left"><i className="pi pi-search" />
        <InputText type="search" onInput={(e) => setGlobalFilter(e.currentTarget.value)} placeholder="Search..." /> </span>
        </div>
    );

    const deleteItemDialogFooter = ( <>
        <Button label="No" icon="pi pi-times" text onClick={hideDeleteItemDialog} />
        <Button label="Yes" icon="pi pi-check" text onClick={deleteItem} /> < />
    );

    const deleteItemsDialogFooter = ( <>
        <Button label="No" icon="pi pi-times" text onClick={hideDeleteItemsDialog} />
        <Button label="Yes" icon="pi pi-check" text onClick={deleteSelectedItems} /> < />
    );

return (
    <div className="grid crud-demo">
        <div className="col-12">
            <div className="card">
                <Toast ref={toast} />
                <Toolbar className="mb-4" left={leftToolbarTemplate} right={rightToolbarTemplate}></Toolbar>
                {findByCriteriaShow && (
                <Card>
                    <div className="search-container">
                        <div className="grid">
                                        <span className="p-float-label mr-3 align-search-items mt-4">
                                        <InputText id="1" value={criteria.ref} onChange={(e) => setCriteria({ ...criteria, ref: e.target.value })} />
                                        <label htmlFor="1">Ref</label>
                                        </span>
                                        <span className="p-float-label mr-3 align-search-items mt-4">
                                        <Dropdown id="2" value={criteria.categorieTerrain} options={categorieTerrains} onChange={(e) => setCriteria({ ...criteria, categorieTerrain: e.target.value })} optionLabel="libelle" filter showClear placeholder="CategorieTerrain" />
                                        </span>
                                        <span className="p-float-label mr-3 align-search-items mt-4">
                                        <Dropdown id="3" value={criteria.redevable} options={redevables} onChange={(e) => setCriteria({ ...criteria, redevable: e.target.value })} optionLabel="cin" filter showClear placeholder="Redevable" />
                                        </span>
                        </div>
                        <div style={{ marginTop : '1rem', display: 'flex', justifyContent: 'flex-end' }} >
                            <Button label="Validate" icon="pi pi-sort-amount-down" className="p-button-info mr-2" onClick={handleValidateClick} />
                            <Button label="Cancel" className="p-button-secondary mr-2"  icon="pi pi-times" onClick={handleCancelClick} />
                    </div>
                        </div>
                </Card>
                )}
                <DataTable ref={dt} value={items} selection={selectedItems} onSelectionChange={(e) => setSelectedItems(e.value as TerrainDto[])} dataKey="id" className="datatable-responsive" globalFilter={globalFilter} header={header} responsiveLayout="scroll" >
                    <Column selectionMode="multiple" headerStyle={{ width: '4rem' }}> </Column>
                    
                    <Column field="ref" header="Ref" sortable></Column>
                    
                    
                    <Column field="categorieTerrain.libelle" header="CategorieTerrain" sortable></Column>
                    
                    
                    <Column field="redevable.cin" header="Redevable" sortable></Column>
                    
                    <Column header="Actions" body={actionBodyTemplate}></Column>
                </DataTable>
                <div className="p-d-flex p-ai-center p-jc-between">
                    <Paginator onPageChange={onPage} first={first} rows={rows} totalRecords={totalRecords} />
                </div>
                <Create visible={showCreateDialog} onClose={() => setShowCreateDialog(false)} add={add} showToast={toast} list={items} />
                <Edit  visible={showEditDialog} onClose={() =>  { setShowEditDialog(false); setSelectedItem(null); }} showToast={toast} selectedItem={selectedItem} update={update} />
                <View visible={showViewDialog} onClose={() =>  { setShowViewDialog(false); setSelectedItem(null); }} selectedItem={selectedItem} />
                <Dialog visible={deleteItemDialog} style={{width: '450px'}} header="Confirm" modal footer={deleteItemDialogFooter} onHide={hideDeleteItemDialog}>
                    <div className="flex align-items-center justify-content-center">
                    <i className="pi pi-exclamation-triangle mr-3" style={{fontSize: '2rem'}}/>
                    {item && (<span>Are you sure you want to delete terrain <b>{item.id}</b>?</span>)}
                    </div>
                </Dialog>
                <Dialog visible={deleteItemsDialog} style={{width: '450px'}} header="Confirm" modal footer={deleteItemsDialogFooter} onHide={hideDeleteItemsDialog} >
                    <div className="flex align-items-center justify-content-center">
                    <i className="pi pi-exclamation-triangle mr-3" style={{fontSize: '2rem'}} />
                    {item && <span>Are you sure you want to delete the selected terrains?</span>}
                    </div>
                </Dialog>
            </div>
        </div>
    </div>
);
};
export default List;

// frontend-ang/src/app/module/admin/view/collaborateur/terrain-admin/list-admin/terrain-list-admin.component.ts
import {Component, OnInit} from '@angular/core';
import {TerrainService} from 'src/app/controller/service/Terrain.service';
import {TerrainDto} from 'src/app/controller/model/Terrain.model';
import {TerrainCriteria} from 'src/app/controller/criteria/TerrainCriteria.model';
import {AbstractListController} from 'src/app/zynerator/controller/AbstractListController';
import { environment } from 'src/environments/environment';

import {RedevableDto} from 'src/app/controller/model/Redevable.model';
import {RedevableService} from 'src/app/controller/service/Redevable.service';
import {CategorieTerrainDto} from 'src/app/controller/model/CategorieTerrain.model';
import {CategorieTerrainService} from 'src/app/controller/service/CategorieTerrain.service';


@Component({
  selector: 'app-terrain-list-admin',
  templateUrl: './terrain-list-admin.component.html'
})
export class TerrainListAdminComponent extends AbstractListController<TerrainDto, TerrainCriteria, TerrainService>  implements OnInit {

    fileName = 'Terrain';

    categorieTerrains :Array<CategorieTerrainDto>;
    redevables :Array<RedevableDto>;

constructor( private terrainService: TerrainService , private redevableService: RedevableService, private categorieTerrainService: CategorieTerrainService) {
        super(terrainService);
        this.pdfName='Terrain.pdf';
    }

    ngOnInit() : void {
      this.findPaginatedByCriteria();
      this.initExport();
      this.initCol();
      this.loadCategorieTerrain();
      this.loadRedevable();
    }

    public async loadTerrains(){
        await this.roleService.findAll();
        const isPermistted = await this.roleService.isPermitted('Terrain', 'list');
        isPermistted ? this.service.findAll().subscribe(terrains => this.items = terrains,error=>console.log(error))
        : this.messageService.add({severity: 'error', summary: 'erreur', detail: 'problème d\'autorisation'});
    }


    public initCol() {
        this.cols = [
            {field: 'ref', header: 'Ref'},
            {field: 'categorieTerrain?.libelle', header: 'Categorie terrain'},
            {field: 'redevable?.cin', header: 'Redevable'},
        ];
    }


    public async loadCategorieTerrain(){
        await this.roleService.findAll();
        const isPermistted = await this.roleService.isPermitted('Terrain', 'list');
        isPermistted ? this.categorieTerrainService.findAllOptimized().subscribe(categorieTerrains => this.categorieTerrains = categorieTerrains,error=>console.log(error))
        : this.messageService.add({severity: 'error', summary: 'Erreur', detail: 'Problème de permission'});
    }
    public async loadRedevable(){
        await this.roleService.findAll();
        const isPermistted = await this.roleService.isPermitted('Terrain', 'list');
        isPermistted ? this.redevableService.findAllOptimized().subscribe(redevables => this.redevables = redevables,error=>console.log(error))
        : this.messageService.add({severity: 'error', summary: 'Erreur', detail: 'Problème de permission'});
    }

	public initDuplicate(res: TerrainDto) {
	}

   public prepareColumnExport() : void {
        this.exportData = this.items.map(e => {
            return {
                 'Ref': e.ref ,
                'Categorie terrain': e.categorieTerrain?.libelle ,
                'Redevable': e.redevable?.cin ,
            }
        });

        this.criteriaData = [{
            'Ref': this.criteria.ref ? this.criteria.ref : environment.emptyForExport ,
        //'Categorie terrain': this.criteria.categorieTerrain?.libelle ? this.criteria.categorieTerrain?.libelle : environment.emptyForExport ,
        //'Redevable': this.criteria.redevable?.cin ? this.criteria.redevable?.cin : environment.emptyForExport ,
        }];
      }
}

<div class="grid">
    <div class="col-12">
        <p-toast></p-toast>
        <div class="card">
            <p-toolbar styleClass="mb-4">
                <ng-template pTemplate="left">
                                        <button pButton pRipple label=" {{'new' | translate}}" icon="pi pi-plus" class="p-button-success mr-2 mb-2" (click)="openCreate('Terrain')"></button>
                    <button [disabled]="isSelectionDisabled()" pButton pRipple label=" {{'delete' | translate}}" icon="pi pi-trash" class="p-button-danger mr-2 mb-2" (click)=deleteMultiple()></button>
                    <button pButton pRipple label=" {{'search' | translate}}" icon="pi pi-{{findByCriteriaShow?'angle-down':'angle-right'}}" class="p-button-warning mr-2 mb-2" (click)="this.showSearch()"></button>
                </ng-template>
                <ng-template pTemplate="right">
                    <div class="flex">
                        <p-splitButton label=" {{'export' | translate}}" icon="pi pi-download" styleClass="p-button-help" [model]="excelPdfButons"></p-splitButton>
                    </div>
                </ng-template>

            </p-toolbar>
            <p-toolbar *ngIf="findByCriteriaShow">

                <div class="align-form-search">
                        <span class=" p-float-label mr-3 align-search-items mt-4">
                            <input class="mr-2" pInputText id="1" type="text"  [(ngModel)]="criteria.refLike">
                            <label for="1">{{'Ref' | translate}}</label>
                        </span>
                        <span class=" p-float-label mr-3 align-search-items mt-4">
                            <p-dropdown [options]="categorieTerrains" [(ngModel)]="criteria.categorieTerrain" id="2" [filter]="true"
                                        [showClear]="true"  placeholder="{{'Categorie terrain' | translate}}" optionLabel="libelle">
                            </p-dropdown>
                        </span>
                        <span class=" p-float-label mr-3 align-search-items mt-4">
                            <p-dropdown [options]="redevables" [(ngModel)]="criteria.redevable" id="3" [filter]="true"
                                        [showClear]="true"  placeholder="{{'Redevable' | translate}}" optionLabel="cin">
                            </p-dropdown>
                        </span>
                </div>

                <div class="align-search-button">
                    <button pButton pRipple label="{{'validate' | translate}}" icon="pi pi-sort-amount-down" class="p-button-info mr-2" (click)="findPaginatedByCriteria()"></button>
                </div>
            </p-toolbar>


            <p-table #dt [value]="items" [columns]="cols" [rows]="8" [paginator]="false"
                    [globalFilterFields]="['ref', 'categorieTerrainlibelle', 'redevablecin']" [(selection)]="selections"
                    [rowHover]="true" dataKey="id" styleClass="p-datatable-customers"
                    currentPageReportTemplate="{{'Les éléments de {first} à {last} sur {totalRecords} ' | translate}}"
                    [showCurrentPageReport]="true" [rowsPerPageOptions]="[10,25,50]" selectionMode="multiple">
                <ng-template pTemplate="caption">
                    <div class="flex flex-column flex-row justify-content-between table-header">
                        <h5 class="p-m-0">{{'terrainHeader' | translate}}</h5>
                        <span class="p-input-icon-left ml-auto">
                            <i class="pi pi-search"></i>
                            <input pInputText type="text" placeholder="{{'searchInput' | translate}}" (input)="dt.filterGlobal($event.target.value, 'contains')"/>
                        </span>
                    </div>
                </ng-template>
                <ng-template pTemplate="header">
                    <tr>
                        <th style="width: 3rem">
                            <p-tableHeaderCheckbox></p-tableHeaderCheckbox>
                        </th>
                                
                        <th pSortableColumn="ref">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'Ref' | translate}}</span>
                                <p-sortIcon field="ref"></p-sortIcon>
                                <p-columnFilter type="text" field="element.ref" display="menu" class="ml-auto"></p-columnFilter>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="categorieTerrain">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'Categorie terrain' | translate}}</span>
                                <p-sortIcon field="categorieTerrain"></p-sortIcon>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="redevable">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'Redevable' | translate}}</span>
                                <p-sortIcon field="redevable"></p-sortIcon>
                            </div>
                        </th>
                                
                        <th>Actions</th>
                    </tr>
                </ng-template>
                <ng-template pTemplate="body" let-element>
                    <tr>
                        <td>
                            <p-tableCheckbox [value]="element"></p-tableCheckbox>
                        </td>
                            
                        <td>{{element.ref}}</td>
                            
                            
                        <td>{{element.categorieTerrain?.libelle}}</td>
                            
                            
                        <td>{{element.redevable?.cin}}</td>
                            
                        <td>
                            <button pButton pRipple icon="pi pi-pencil"  class="p-button-rounded p-button-success mr-2" (click)="edit(element)"></button>
                            <button pButton pRipple icon="pi pi-list" class="p-button-rounded p-button-info mr-2" (click)="view(element)"></button>
                            <button pButton pRipple icon="pi pi-trash" class="p-button-rounded p-button-danger mr-2" (click)="delete(element)"></button>
                            <button pButton pRipple icon="pi pi-copy" class="p-button-rounded p-button-raised p-button-warning mr-2" (click)="duplicate(element)"></button>
                            <button pButton pRipple icon="pi pi-download" class="p-button-rounded p-button-secondary" (click)="exportPdf(element)"></button>
                        </td>
                    </tr>
                </ng-template>

                <ng-template pTemplate="summary">
                    <p-paginator  [rows]="10" [totalRecords]="totalRecords" (onPageChange)="onPage($event)"></p-paginator>
                    <div class="p-d-flex p-ai-center p-jc-between">
                        En totale il {{items ? totalRecords == 1 ? 'y a' : 'y a' : 'y a' }} {{items ? totalRecords : 0 }} {{items ? totalRecords == 1 ? 'terrain' : 'terrains' : 0 }}.
                    </div>
                </ng-template>
            </p-table>
        </div>

        <app-terrain-create-admin></app-terrain-create-admin>
        <app-terrain-edit-admin></app-terrain-edit-admin>
        <app-terrain-view-admin></app-terrain-view-admin>
        <p-confirmDialog [style]="{width: '450px'}"></p-confirmDialog>
    </div>
</div>
