// frontend-react/pages/module/admin/view/collaborateur/terrain-admin/view-admin/terrain-view-admin.component.tsx
import {Button} from 'primereact/button';
import {Column} from 'primereact/column';
import {Dropdown} from 'primereact/dropdown';
import {TabView, TabPanel} from 'primereact/tabview';
import {DataTable} from 'primereact/datatable';
import {Dialog} from 'primereact/dialog';
import {InputNumber, InputNumberChangeEvent} from 'primereact/inputnumber';
import {InputText} from 'primereact/inputtext';
import {classNames} from 'primereact/utils';
import { InputTextarea } from 'primereact/inputtextarea';
import {AxiosResponse} from 'axios';
import React, {useEffect, useState} from 'react';
import {Calendar, CalendarChangeEvent} from 'primereact/calendar';
import { format } from 'date-fns';
import { InputSwitch } from "primereact/inputswitch";
import {MultiSelect} from "primereact/multiselect";
import  {TerrainDto}  from '/pages/controller/model/Terrain.model';

const View = ({visible,onClose,selectedItem}) => {

    const emptyItem = new TerrainDto();
    const [item, setItem] = useState<TerrainDto>(emptyItem);
    const [submitted, setSubmitted] = useState(false);
    const [activeIndex, setActiveIndex] = useState<number>(0);

    useEffect(() => {
        setItem(selectedItem ? { ...selectedItem } : { ...emptyItem });
    }, [selectedItem]);

    const onTabChange = (e: { index: number }) => {
        setActiveIndex(e.index);
    };

    const hideDialog = () => {
        setSubmitted(false);
        onClose();
    };

    const itemDialogFooter = ( <>
        <Button label="Cancel" icon="pi pi-times" text onClick={hideDialog} /> < />
    );

return(
<Dialog visible={visible} style={{width: '70vw'}} header="Terrain Details" modal className="p-fluid" footer={itemDialogFooter} onHide={hideDialog} >
<TabView activeIndex={activeIndex} onTabChange={onTabChange}>
<TabPanel header="Terrain">
    <div className="formgrid grid">

            <div className="field col-6">
                <label htmlFor="ref">Ref</label>
                <InputText id="ref" value={selectedItem?.ref} disabled   />
            </div>

                <div className="field col-6">
                    <label htmlFor="categorieTerrain">CategorieTerrain</label>
                    <Dropdown  id="categorieTerrainDropdown"  value={selectedItem?.categorieTerrain?.libelle}  disabled  />
                </div>
                <div className="field col-6">
                    <label htmlFor="redevable">Redevable</label>
                    <Dropdown  id="redevableDropdown"  value={selectedItem?.redevable?.cin}  disabled  />
                </div>
        </div>
</TabPanel>
</TabView>
</Dialog>
);
};
export default View;

// frontend-ang/src/app/module/admin/view/collaborateur/terrain-admin/view-admin/terrain-view-admin.component.ts
import {Component, OnInit} from '@angular/core';


import {AbstractViewController} from 'src/app/zynerator/controller/AbstractViewController';
import { environment } from 'src/environments/environment';

import {TerrainService} from 'src/app/controller/service/Terrain.service';
import {TerrainDto} from 'src/app/controller/model/Terrain.model';
import {TerrainCriteria} from 'src/app/controller/criteria/TerrainCriteria.model';

import {RedevableDto} from 'src/app/controller/model/Redevable.model';
import {RedevableService} from 'src/app/controller/service/Redevable.service';
import {CategorieTerrainDto} from 'src/app/controller/model/CategorieTerrain.model';
import {CategorieTerrainService} from 'src/app/controller/service/CategorieTerrain.service';
@Component({
  selector: 'app-terrain-view-admin',
  templateUrl: './terrain-view-admin.component.html'
})
export class TerrainViewAdminComponent extends AbstractViewController<TerrainDto, TerrainCriteria, TerrainService> implements OnInit {


    constructor(private terrainService: TerrainService, private redevableService: RedevableService, private categorieTerrainService: CategorieTerrainService){
        super(terrainService);
    }

    ngOnInit(): void {
        this.categorieTerrain = new CategorieTerrainDto();
        this.categorieTerrainService.findAll().subscribe((data) => this.categorieTerrains = data);
        this.redevable = new RedevableDto();
        this.redevableService.findAll().subscribe((data) => this.redevables = data);
    }


    get redevable(): RedevableDto {
       return this.redevableService.item;
    }
    set redevable(value: RedevableDto) {
        this.redevableService.item = value;
    }
    get redevables():Array<RedevableDto> {
       return this.redevableService.items;
    }
    set redevables(value: Array<RedevableDto>) {
        this.redevableService.items = value;
    }
    get categorieTerrain(): CategorieTerrainDto {
       return this.categorieTerrainService.item;
    }
    set categorieTerrain(value: CategorieTerrainDto) {
        this.categorieTerrainService.item = value;
    }
    get categorieTerrains():Array<CategorieTerrainDto> {
       return this.categorieTerrainService.items;
    }
    set categorieTerrains(value: Array<CategorieTerrainDto>) {
        this.categorieTerrainService.items = value;
    }


}


<p-dialog [(visible)]="viewDialog" [style]="{width: '70vw'}" header="{{'terrainTabPan' | translate}}" [modal]="true" styleClass="p-fluid">
    <ng-template pTemplate="content">
        <p-tabView>
            <p-tabPanel header="{{'terrainTabPan' | translate}}">
                <div class="grid">
                    <div class="field col-12 md:col-6">
                        <label for="1">{{'Ref' | translate}}</label>
                        <input class="mb-2 mr-2" type="text" pInputText [disabled]="true" placeholder="{{'Ref' | translate}}" autofocus  id="1" [(ngModel)]="item.ref">
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="2">{{'Categorie terrain' | translate}}</label>
                        <p-dropdown [options]="categorieTerrains" [(ngModel)]="item.categorieTerrain" id="2" [disabled]="true" optionLabel="libelle" placeholder="{{'Categorie terrain' | translate}}"></p-dropdown>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="3">{{'Redevable' | translate}}</label>
                        <p-dropdown [options]="redevables" [(ngModel)]="item.redevable" id="3" [disabled]="true" optionLabel="cin" placeholder="{{'Redevable' | translate}}"></p-dropdown>
                    </div>
                </div>
            </p-tabPanel>

        </p-tabView>

    </ng-template>

    <ng-template pTemplate="footer" >
        <div class="grid-footer">
            <div>
                <button pButton pRipple label="Annuler" icon="pi pi-times" class="p-button-outlined" (click)="hideViewDialog()"></button>
            </div>
        </div>
    </ng-template>
</p-dialog>
