// frontend-react/pages/module/admin/view/tnb/tax-tnb-admin/list-admin/tax-tnb-list-admin.component.tsx
import {Button} from 'primereact/button';
import {Column} from 'primereact/column';
import 'primereact/resources/themes/saga-blue/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import {DataTable} from 'primereact/datatable';
import {Dialog} from 'primereact/dialog';
import {FileUpload} from 'primereact/fileupload';
import {InputText} from 'primereact/inputtext';
import {Toast} from 'primereact/toast';
import {Toolbar} from 'primereact/toolbar';
import React, {useEffect, useRef, useState} from 'react';
import { Paginator } from 'primereact/paginator';
import {BaseCriteria} from '/pages/zynerator/criteria/BaseCriteria.model';
import {MessageService} from '/pages/controller/service/MessageService';
import {Card} from "primereact/card";
import {Calendar} from "primereact/calendar";
import {InputNumber} from "primereact/inputnumber";
import {Dropdown} from "primereact/dropdown";
import {AxiosResponse} from "axios";

import {TaxTnbService} from '/pages/controller/service/TaxTnb.service';
import {TaxTnbDto}  from '/pages/controller/model/TaxTnb.model';
import {TaxTnbCriteria} from "/pages/controller/criteria/TaxTnbCriteria.model";

import {TerrainDto} from '/pages/controller/model/Terrain.model';
import {TerrainService} from '/pages/controller/service/Terrain.service';
import {RedevableDto} from '/pages/controller/model/Redevable.model';
import {RedevableService} from '/pages/controller/service/Redevable.service';
import {TauxTaxTnbDto} from '/pages/controller/model/TauxTaxTnb.model';
import {TauxTaxTnbService} from '/pages/controller/service/TauxTaxTnb.service';

import Edit from '/pages/module/admin/view/tnb/tax-tnb-admin/edit-admin/tax-tnb-edit-admin.component';
import Create from '/pages/module/admin/view/tnb/tax-tnb-admin/create-admin/tax-tnb-create-admin.component';
import View from '/pages/module/admin/view/tnb/tax-tnb-admin/view-admin/tax-tnb-view-admin.component';

const List = () => {

    const emptyItem = new TaxTnbDto();
    const [items, setItems] = useState<TaxTnbDto[]>([]);
    const [deleteItemDialog, setDeleteItemDialog] = useState(false);
    const [deleteItemsDialog, setDeleteItemsDialog] = useState(false);
    const [item, setItem] = useState<TaxTnbDto>(emptyItem);
    const [selectedItems, setSelectedItems] = useState<TaxTnbDto[]>([]);
    const [globalFilter, setGlobalFilter] = useState('');
    const [showCreateDialog, setShowCreateDialog] = useState<boolean>(false);
    const [showEditDialog, setShowEditDialog] = useState<boolean>(false);
    const [showViewDialog, setShowViewDialog] = useState<boolean>(false);
    const [selectedItem, setSelectedItem] = useState<TaxTnbDto | null>(null);
    const [rows, setRows] = useState<number>(10);
    const [totalRecords, setTotalRecords] = useState(0);
    const [criteria, setCriteria] = useState(new TaxTnbCriteria());
    const [first, setFirst] = useState(0);
    const toast = useRef<Toast>();
    const dt = useRef<DataTable<TaxTnbDto[]>>();
    const [findByCriteriaShow, setFindByCriteriaShow] = useState(false);
    const [isSearchTriggered, setIsSearchTriggered] = useState(false);

    const [terrains, setTerrains] = useState<TerrainDto[]>([]);
    type TerrainResponse = AxiosResponse<TerrainDto[]>;
    const [redevables, setRedevables] = useState<RedevableDto[]>([]);
    type RedevableResponse = AxiosResponse<RedevableDto[]>;
    const [tauxTaxTnbs, setTauxTaxTnbs] = useState<TauxTaxTnbDto[]>([]);
    type TauxTaxTnbResponse = AxiosResponse<TauxTaxTnbDto[]>;

    const showSearch = () => { setFindByCriteriaShow(!findByCriteriaShow); };

    const handleValidateClick = () => {setIsSearchTriggered(true);};

    const handleCancelClick = () => {
        setCriteria(new TaxTnbCriteria());
        setIsSearchTriggered(true);
    };

    useEffect(() => {
        const fetchData = async () => {
            try {
                const [redevablesResponse ,terrainsResponse ,tauxTaxTnbsResponse ] = await Promise.all<RedevableResponse,TerrainResponse,TauxTaxTnbResponse>([
                ]);
                setRedevables(redevablesResponse.data);
                setTerrains(terrainsResponse.data);
                setTauxTaxTnbs(tauxTaxTnbsResponse.data);
            } catch (error) {
                console.error(error);
            }
        };
        if (isSearchTriggered) {
            fetchItems(criteria);
            setIsSearchTriggered(false);
        }
        fetchData();
        fetchItems(criteria);
    }, [isSearchTriggered]);

    const fetchItems = async (criteria) => {
        try {
            const response = await TaxTnbService.findPaginatedByCriteria(criteria);
            const paginatedItems = response.data;
            setTotalRecords(paginatedItems.dataSize);
            setItems(paginatedItems.list);
        } catch (error) {
            console.log(error);
        }
    };

    const onPage = (event) => {
        const updatedCriteria = { ...criteria, page: event.page,maxResults: event.rows };
        setCriteria(updatedCriteria);
        setFirst(event.first);
        fetchItems(updatedCriteria);
    };

    const showCreateModal = (): void => {
        setShowCreateDialog(true);
    };

    const showEditModal = (item: TaxTnbDto) => {
        setSelectedItem(item);
        setShowEditDialog(true);
    };

    const showViewModal = (item: TaxTnbDto) => {
        setSelectedItem(item);
        setShowViewDialog(true);
    };

    const add = (item) => {
        setItems([...items, item]);
    };

    const update = (updatedItem: TaxTnbDto) => {
        const updatedList = items.map((item) => {
            if (item.id === updatedItem.id) { return updatedItem; }
            return item;
        });
        setItems(updatedList);
    };

   const hideDeleteItemDialog = () => {
        setDeleteItemDialog(false);
   };

   const hideDeleteItemsDialog = () => {
        setDeleteItemsDialog(false);
   };

    const confirmDeleteItem = (item: TaxTnbDto) => {
        setSelectedItem(item);
        setDeleteItemDialog(true);
    };

    const deleteItem = async () => {
        try{
            await TaxTnbService.delete(selectedItem?.id);
            setDeleteItemDialog(false);
            setItem(emptyItem);
            let _items = items.filter((val) => val.id !== selectedItem?.id);
            setItems(_items);
            MessageService.showToast(toast, { severity: 'success', summary: 'Successful', detail: 'TaxTnb Deleted', life: 3000 });
        } catch (error) {
            console.log(error);
        }
    };

    const exportCSV = () => {
        dt.current?.exportCSV();
    };

    const confirmDeleteSelected = () => {
        setDeleteItemsDialog(true);
    };

    const deleteSelectedItems = async () => {
        await TaxTnbService.deleteList(selectedItems);
        let _items = items.filter((val) => !selectedItems.includes(val));
        setItems(_items);
        setDeleteItemsDialog(false);
        setSelectedItems(null);
        MessageService.showToast(toast, { severity: 'success', summary: 'Successful', detail: 'TaxTnbs Deleted', life: 3000 });
    };

   const leftToolbarTemplate = () => {
       return (
           <React.Fragment>
               <div className="my-2">
                   <Button label="New" icon="pi pi-plus" severity="success" className=" mr-2" onClick={ showCreateModal} />
                   <Button label="Delete" icon="pi pi-trash" severity="danger" className=" mr-2" onClick={confirmDeleteSelected} disabled={!selectedItems || !selectedItems.length} />
                   <Button label="Search" icon={`pi pi-${findByCriteriaShow ? 'angle-down' : 'angle-right'}`} className=" mr-2" severity="warning" onClick={showSearch} />
               </div>
           </React.Fragment>
       );
   };

   const rightToolbarTemplate = () => {
       return (
           <React.Fragment>
               <FileUpload mode="basic" accept="image/*" maxFileSize={1000000} chooseLabel="Import" className="mr-2 inline-block" />
               <Button label="Export" icon="pi pi-upload" severity="help" onClick={exportCSV} />
           </React.Fragment>
       );
   };

    const actionBodyTemplate = (rowData: TaxTnbDto) => {
       return ( <>
           <Button icon="pi pi-pencil" rounded severity="success" className="mr-1" onClick={() => showEditModal(rowData)} />
           <Button icon="pi pi-trash" rounded  severity="danger" className="mr-1"  onClick={() => confirmDeleteItem(rowData)} />
           <Button icon="pi pi-eye" rounded severity="info" className="mr-1" onClick={() => showViewModal(rowData)} /> < />
       );
    };

    const header = (
        <div className="flex flex-column md:flex-row md:justify-content-between md:align-items-center">
        <h5 className="m-0">Manage tax tnbs</h5>
        <span className="block mt-2 md:mt-0 p-input-icon-left"><i className="pi pi-search" />
        <InputText type="search" onInput={(e) => setGlobalFilter(e.currentTarget.value)} placeholder="Search..." /> </span>
        </div>
    );

    const deleteItemDialogFooter = ( <>
        <Button label="No" icon="pi pi-times" text onClick={hideDeleteItemDialog} />
        <Button label="Yes" icon="pi pi-check" text onClick={deleteItem} /> < />
    );

    const deleteItemsDialogFooter = ( <>
        <Button label="No" icon="pi pi-times" text onClick={hideDeleteItemsDialog} />
        <Button label="Yes" icon="pi pi-check" text onClick={deleteSelectedItems} /> < />
    );

return (
    <div className="grid crud-demo">
        <div className="col-12">
            <div className="card">
                <Toast ref={toast} />
                <Toolbar className="mb-4" left={leftToolbarTemplate} right={rightToolbarTemplate}></Toolbar>
                {findByCriteriaShow && (
                <Card>
                    <div className="search-container">
                        <div className="grid">
                                        <span className="p-float-label mr-3 align-search-items mt-4">
                                        <InputNumber id="1-1" value={criteria.anneeMin} onChange={(e) => setCriteria({ ...criteria, anneeMin: e.value })} mode="decimal" />
                                        <label htmlFor="1-1">Annee Min</label>
                                        </span>
                                        <span className="p-float-label mr-3 align-search-items mt-4">
                                        <InputNumber id="1-2" value={criteria.anneeMax} onChange={(e) => setCriteria({ ...criteria, anneeMax: e.value })} mode="decimal" />
                                        <label htmlFor="1-2">Annee Max</label>
                                        </span>
                                        <span className="p-float-label mr-3 align-search-items mt-4">
                                        <InputNumber id="2-1" value={criteria.montantBaseMin} onChange={(e) => setCriteria({ ...criteria, montantBaseMin: e.value })} mode="decimal" />
                                        <label htmlFor="2-1">MontantBase Min</label>
                                        </span>
                                        <span className="p-float-label mr-3 align-search-items mt-4">
                                        <InputNumber id="2-2" value={criteria.montantBaseMax} onChange={(e) => setCriteria({ ...criteria, montantBaseMax: e.value })} mode="decimal" />
                                        <label htmlFor="2-2">MontantBase Max</label>
                                        </span>
                                        <span className="p-float-label mr-3 align-search-items mt-4">
                                        <InputNumber id="3-1" value={criteria.mantantRetardMin} onChange={(e) => setCriteria({ ...criteria, mantantRetardMin: e.value })} mode="decimal" />
                                        <label htmlFor="3-1">MantantRetard Min</label>
                                        </span>
                                        <span className="p-float-label mr-3 align-search-items mt-4">
                                        <InputNumber id="3-2" value={criteria.mantantRetardMax} onChange={(e) => setCriteria({ ...criteria, mantantRetardMax: e.value })} mode="decimal" />
                                        <label htmlFor="3-2">MantantRetard Max</label>
                                        </span>
                                        <span className="p-float-label mr-3 align-search-items mt-4">
                                        <InputNumber id="4-1" value={criteria.nombreMoisRetardMin} onChange={(e) => setCriteria({ ...criteria, nombreMoisRetardMin: e.value })} mode="decimal" />
                                        <label htmlFor="4-1">NombreMoisRetard Min</label>
                                        </span>
                                        <span className="p-float-label mr-3 align-search-items mt-4">
                                        <InputNumber id="4-2" value={criteria.nombreMoisRetardMax} onChange={(e) => setCriteria({ ...criteria, nombreMoisRetardMax: e.value })} mode="decimal" />
                                        <label htmlFor="4-2">NombreMoisRetard Max</label>
                                        </span>
                                        <span className="p-float-label mr-3 align-search-items mt-4">
                                        <InputNumber id="5-1" value={criteria.montantTotalMin} onChange={(e) => setCriteria({ ...criteria, montantTotalMin: e.value })} mode="decimal" />
                                        <label htmlFor="5-1">MontantTotal Min</label>
                                        </span>
                                        <span className="p-float-label mr-3 align-search-items mt-4">
                                        <InputNumber id="5-2" value={criteria.montantTotalMax} onChange={(e) => setCriteria({ ...criteria, montantTotalMax: e.value })} mode="decimal" />
                                        <label htmlFor="5-2">MontantTotal Max</label>
                                        </span>
                                        <span className="p-float-label mr-3 align-search-items mt-4">
                                        <Calendar id="6-1" value={criteria.datePresentationFrom} onChange={(e) => setCriteria({ ...criteria, datePresentationFrom: e.value as Date })} dateFormat="dd-MM-yy" />
                                        <label htmlFor="6-1">DatePresentation Min</label>
                                        </span>
                                        <span className="p-float-label mr-3 align-search-items mt-4">
                                        <Calendar id="6-2" value={criteria.datePresentationTo} onChange={(e) => setCriteria({ ...criteria, datePresentationTo: e.value as Date })} dateFormat="dd-MM-yy" />
                                        <label htmlFor="6-2">DatePresentation Max</label>
                                        </span>
                                        <span className="p-float-label mr-3 align-search-items mt-4">
                                        <Calendar id="7-1" value={criteria.dateTaxeTnbFrom} onChange={(e) => setCriteria({ ...criteria, dateTaxeTnbFrom: e.value as Date })} dateFormat="dd-MM-yy" />
                                        <label htmlFor="7-1">DateTaxeTnb Min</label>
                                        </span>
                                        <span className="p-float-label mr-3 align-search-items mt-4">
                                        <Calendar id="7-2" value={criteria.dateTaxeTnbTo} onChange={(e) => setCriteria({ ...criteria, dateTaxeTnbTo: e.value as Date })} dateFormat="dd-MM-yy" />
                                        <label htmlFor="7-2">DateTaxeTnb Max</label>
                                        </span>
                                        <span className="p-float-label mr-3 align-search-items mt-4">
                                        <Dropdown id="8" value={criteria.redevable} options={redevables} onChange={(e) => setCriteria({ ...criteria, redevable: e.target.value })} optionLabel="cin" filter showClear placeholder="Redevable" />
                                        </span>
                                        <span className="p-float-label mr-3 align-search-items mt-4">
                                        <Dropdown id="9" value={criteria.terrain} options={terrains} onChange={(e) => setCriteria({ ...criteria, terrain: e.target.value })} optionLabel="ref" filter showClear placeholder="Terrain" />
                                        </span>
                                        <span className="p-float-label mr-3 align-search-items mt-4">
                                        <Dropdown id="10" value={criteria.tauxTaxTnb} options={tauxTaxTnbs} onChange={(e) => setCriteria({ ...criteria, tauxTaxTnb: e.target.value })} optionLabel="id" filter showClear placeholder="TauxTaxTnb" />
                                        </span>
                        </div>
                        <div style={{ marginTop : '1rem', display: 'flex', justifyContent: 'flex-end' }} >
                            <Button label="Validate" icon="pi pi-sort-amount-down" className="p-button-info mr-2" onClick={handleValidateClick} />
                            <Button label="Cancel" className="p-button-secondary mr-2"  icon="pi pi-times" onClick={handleCancelClick} />
                    </div>
                        </div>
                </Card>
                )}
                <DataTable ref={dt} value={items} selection={selectedItems} onSelectionChange={(e) => setSelectedItems(e.value as TaxTnbDto[])} dataKey="id" className="datatable-responsive" globalFilter={globalFilter} header={header} responsiveLayout="scroll" >
                    <Column selectionMode="multiple" headerStyle={{ width: '4rem' }}> </Column>
                    
                    <Column field="annee" header="Annee" sortable></Column>
                    
                    
                    <Column field="montantBase" header="MontantBase" sortable></Column>
                    
                    
                    <Column field="mantantRetard" header="MantantRetard" sortable></Column>
                    
                    
                    <Column field="nombreMoisRetard" header="NombreMoisRetard" sortable></Column>
                    
                    
                    <Column field="montantTotal" header="MontantTotal" sortable></Column>
                    
                    
                    <Column field="datePresentation" header="DatePresentation" sortable></Column>
                    
                    
                    <Column field="dateTaxeTnb" header="DateTaxeTnb" sortable></Column>
                    
                    
                    <Column field="redevable.cin" header="Redevable" sortable></Column>
                    
                    
                    <Column field="terrain.ref" header="Terrain" sortable></Column>
                    
                     <!-- 
                    <Column field="tauxTaxTnb.id" header="TauxTaxTnb" sortable></Column>
                     --> 
                    <Column header="Actions" body={actionBodyTemplate}></Column>
                </DataTable>
                <div className="p-d-flex p-ai-center p-jc-between">
                    <Paginator onPageChange={onPage} first={first} rows={rows} totalRecords={totalRecords} />
                </div>
                <Create visible={showCreateDialog} onClose={() => setShowCreateDialog(false)} add={add} showToast={toast} list={items} />
                <Edit  visible={showEditDialog} onClose={() =>  { setShowEditDialog(false); setSelectedItem(null); }} showToast={toast} selectedItem={selectedItem} update={update} />
                <View visible={showViewDialog} onClose={() =>  { setShowViewDialog(false); setSelectedItem(null); }} selectedItem={selectedItem} />
                <Dialog visible={deleteItemDialog} style={{width: '450px'}} header="Confirm" modal footer={deleteItemDialogFooter} onHide={hideDeleteItemDialog}>
                    <div className="flex align-items-center justify-content-center">
                    <i className="pi pi-exclamation-triangle mr-3" style={{fontSize: '2rem'}}/>
                    {item && (<span>Are you sure you want to delete tax tnb <b>{item.id}</b>?</span>)}
                    </div>
                </Dialog>
                <Dialog visible={deleteItemsDialog} style={{width: '450px'}} header="Confirm" modal footer={deleteItemsDialogFooter} onHide={hideDeleteItemsDialog} >
                    <div className="flex align-items-center justify-content-center">
                    <i className="pi pi-exclamation-triangle mr-3" style={{fontSize: '2rem'}} />
                    {item && <span>Are you sure you want to delete the selected tax tnbs?</span>}
                    </div>
                </Dialog>
            </div>
        </div>
    </div>
);
};
export default List;

// frontend-ang/src/app/module/admin/view/tnb/tax-tnb-admin/list-admin/tax-tnb-list-admin.component.ts
import {Component, OnInit} from '@angular/core';
import {TaxTnbService} from 'src/app/controller/service/TaxTnb.service';
import {TaxTnbDto} from 'src/app/controller/model/TaxTnb.model';
import {TaxTnbCriteria} from 'src/app/controller/criteria/TaxTnbCriteria.model';
import {AbstractListController} from 'src/app/zynerator/controller/AbstractListController';
import { environment } from 'src/environments/environment';

import {RedevableDto} from 'src/app/controller/model/Redevable.model';
import {RedevableService} from 'src/app/controller/service/Redevable.service';
import {TauxTaxTnbDto} from 'src/app/controller/model/TauxTaxTnb.model';
import {TauxTaxTnbService} from 'src/app/controller/service/TauxTaxTnb.service';
import {TerrainDto} from 'src/app/controller/model/Terrain.model';
import {TerrainService} from 'src/app/controller/service/Terrain.service';


@Component({
  selector: 'app-tax-tnb-list-admin',
  templateUrl: './tax-tnb-list-admin.component.html'
})
export class TaxTnbListAdminComponent extends AbstractListController<TaxTnbDto, TaxTnbCriteria, TaxTnbService>  implements OnInit {

    fileName = 'TaxTnb';

    redevables :Array<RedevableDto>;
    terrains :Array<TerrainDto>;
    tauxTaxTnbs :Array<TauxTaxTnbDto>;

constructor( private taxTnbService: TaxTnbService , private redevableService: RedevableService, private tauxTaxTnbService: TauxTaxTnbService, private terrainService: TerrainService) {
        super(taxTnbService);
    }

    ngOnInit() : void {
      this.findPaginatedByCriteria();
      this.initExport();
      this.initCol();
      this.loadRedevable();
      this.loadTerrain();
      this.loadTauxTaxTnb();
    }

    public async loadTaxTnbs(){
        await this.roleService.findAll();
        const isPermistted = await this.roleService.isPermitted('TaxTnb', 'list');
        isPermistted ? this.service.findAll().subscribe(taxTnbs => this.items = taxTnbs,error=>console.log(error))
        : this.messageService.add({severity: 'error', summary: 'erreur', detail: 'problème d\'autorisation'});
    }


    public initCol() {
        this.cols = [
            {field: 'annee', header: 'Annee'},
            {field: 'montantBase', header: 'Montant base'},
            {field: 'mantantRetard', header: 'Mantant retard'},
            {field: 'nombreMoisRetard', header: 'Nombre mois retard'},
            {field: 'montantTotal', header: 'Montant total'},
            {field: 'datePresentation', header: 'Date presentation'},
            {field: 'dateTaxeTnb', header: 'Date taxe tnb'},
            {field: 'redevable?.cin', header: 'Redevable'},
            {field: 'terrain?.ref', header: 'Terrain'},
            {field: 'tauxTaxTnb?.id', header: 'Taux tax tnb'},
        ];
    }


    public async loadRedevable(){
        await this.roleService.findAll();
        const isPermistted = await this.roleService.isPermitted('TaxTnb', 'list');
        isPermistted ? this.redevableService.findAllOptimized().subscribe(redevables => this.redevables = redevables,error=>console.log(error))
        : this.messageService.add({severity: 'error', summary: 'Erreur', detail: 'Problème de permission'});
    }
    public async loadTerrain(){
        await this.roleService.findAll();
        const isPermistted = await this.roleService.isPermitted('TaxTnb', 'list');
        isPermistted ? this.terrainService.findAllOptimized().subscribe(terrains => this.terrains = terrains,error=>console.log(error))
        : this.messageService.add({severity: 'error', summary: 'Erreur', detail: 'Problème de permission'});
    }
    public async loadTauxTaxTnb(){
        await this.roleService.findAll();
        const isPermistted = await this.roleService.isPermitted('TaxTnb', 'list');
        isPermistted ? this.tauxTaxTnbService.findAll().subscribe(tauxTaxTnbs => this.tauxTaxTnbs = tauxTaxTnbs,error=>console.log(error))
        : this.messageService.add({severity: 'error', summary: 'Erreur', detail: 'Problème de permission'});
    }

	public initDuplicate(res: TaxTnbDto) {
	}

   public prepareColumnExport() : void {
        this.exportData = this.items.map(e => {
            return {
                 'Annee': e.annee ,
                 'Montant base': e.montantBase ,
                 'Mantant retard': e.mantantRetard ,
                 'Nombre mois retard': e.nombreMoisRetard ,
                 'Montant total': e.montantTotal ,
                'Date presentation': this.datePipe.transform(e.datePresentation , 'dd/MM/yyyy hh:mm'),
                'Date taxe tnb': this.datePipe.transform(e.dateTaxeTnb , 'dd/MM/yyyy hh:mm'),
                'Redevable': e.redevable?.cin ,
                'Terrain': e.terrain?.ref ,
                'Taux tax tnb': e.tauxTaxTnb?.id ,
            }
        });

        this.criteriaData = [{
            'Annee Min': this.criteria.anneeMin ? this.criteria.anneeMin : environment.emptyForExport ,
            'Annee Max': this.criteria.anneeMax ? this.criteria.anneeMax : environment.emptyForExport ,
            'Montant base Min': this.criteria.montantBaseMin ? this.criteria.montantBaseMin : environment.emptyForExport ,
            'Montant base Max': this.criteria.montantBaseMax ? this.criteria.montantBaseMax : environment.emptyForExport ,
            'Mantant retard Min': this.criteria.mantantRetardMin ? this.criteria.mantantRetardMin : environment.emptyForExport ,
            'Mantant retard Max': this.criteria.mantantRetardMax ? this.criteria.mantantRetardMax : environment.emptyForExport ,
            'Nombre mois retard Min': this.criteria.nombreMoisRetardMin ? this.criteria.nombreMoisRetardMin : environment.emptyForExport ,
            'Nombre mois retard Max': this.criteria.nombreMoisRetardMax ? this.criteria.nombreMoisRetardMax : environment.emptyForExport ,
            'Montant total Min': this.criteria.montantTotalMin ? this.criteria.montantTotalMin : environment.emptyForExport ,
            'Montant total Max': this.criteria.montantTotalMax ? this.criteria.montantTotalMax : environment.emptyForExport ,
            'Date presentation Min': this.criteria.datePresentationFrom ? this.datePipe.transform(this.criteria.datePresentationFrom , this.dateFormat) : environment.emptyForExport ,
            'Date presentation Max': this.criteria.datePresentationTo ? this.datePipe.transform(this.criteria.datePresentationTo , this.dateFormat) : environment.emptyForExport ,
            'Date taxe tnb Min': this.criteria.dateTaxeTnbFrom ? this.datePipe.transform(this.criteria.dateTaxeTnbFrom , this.dateFormat) : environment.emptyForExport ,
            'Date taxe tnb Max': this.criteria.dateTaxeTnbTo ? this.datePipe.transform(this.criteria.dateTaxeTnbTo , this.dateFormat) : environment.emptyForExport ,
        //'Redevable': this.criteria.redevable?.cin ? this.criteria.redevable?.cin : environment.emptyForExport ,
        //'Terrain': this.criteria.terrain?.ref ? this.criteria.terrain?.ref : environment.emptyForExport ,
        //'Taux tax tnb': this.criteria.tauxTaxTnb?.id ? this.criteria.tauxTaxTnb?.id : environment.emptyForExport ,
        }];
      }
}

<div class="grid">
    <div class="col-12">
        <p-toast></p-toast>
        <div class="card">
            <p-toolbar styleClass="mb-4">
                <ng-template pTemplate="left">
                                        <button pButton pRipple label=" {{'new' | translate}}" icon="pi pi-plus" class="p-button-success mr-2 mb-2" (click)="openCreate('TaxTnb')"></button>
                    <button [disabled]="isSelectionDisabled()" pButton pRipple label=" {{'delete' | translate}}" icon="pi pi-trash" class="p-button-danger mr-2 mb-2" (click)=deleteMultiple()></button>
                    <button pButton pRipple label=" {{'search' | translate}}" icon="pi pi-{{findByCriteriaShow?'angle-down':'angle-right'}}" class="p-button-warning mr-2 mb-2" (click)="this.showSearch()"></button>
                </ng-template>
                <ng-template pTemplate="right">
                    <div class="flex">
                        <p-splitButton label=" {{'export' | translate}}" icon="pi pi-download" styleClass="p-button-help" [model]="excelPdfButons"></p-splitButton>
                    </div>
                </ng-template>

            </p-toolbar>
            <p-toolbar *ngIf="findByCriteriaShow">

                <div class="align-form-search">
                        <span class=" p-float-label mr-3 align-search-items mt-4">
                            <p-inputNumber class="mr-2" mode="decimal" [(ngModel)]="criteria.anneeMin" id="1-1"></p-inputNumber>
                            <label for="1-1">{{'Annee' | translate}} Min</label>
                        </span>
                       <span class=" p-float-label mr-3 align-search-items mt-4">
                            <p-inputNumber class="mr-2" mode="decimal" [(ngModel)]="criteria.anneeMax" id="1-2"></p-inputNumber>
                            <label for="1-2">{{'Annee' | translate}} Max</label>
                       </span>
                        <span class=" p-float-label mr-3 align-search-items mt-4">
                            <p-inputNumber class="mr-2" mode="decimal" [(ngModel)]="criteria.montantBaseMin" id="2-1"></p-inputNumber>
                            <label for="2-1">{{'Montant base' | translate}} Min</label>
                        </span>
                       <span class=" p-float-label mr-3 align-search-items mt-4">
                            <p-inputNumber class="mr-2" mode="decimal" [(ngModel)]="criteria.montantBaseMax" id="2-2"></p-inputNumber>
                            <label for="2-2">{{'Montant base' | translate}} Max</label>
                       </span>
                        <span class=" p-float-label mr-3 align-search-items mt-4">
                            <p-inputNumber class="mr-2" mode="decimal" [(ngModel)]="criteria.mantantRetardMin" id="3-1"></p-inputNumber>
                            <label for="3-1">{{'Mantant retard' | translate}} Min</label>
                        </span>
                       <span class=" p-float-label mr-3 align-search-items mt-4">
                            <p-inputNumber class="mr-2" mode="decimal" [(ngModel)]="criteria.mantantRetardMax" id="3-2"></p-inputNumber>
                            <label for="3-2">{{'Mantant retard' | translate}} Max</label>
                       </span>
                        <span class=" p-float-label mr-3 align-search-items mt-4">
                            <p-inputNumber class="mr-2" mode="decimal" [(ngModel)]="criteria.nombreMoisRetardMin" id="4-1"></p-inputNumber>
                            <label for="4-1">{{'Nombre mois retard' | translate}} Min</label>
                        </span>
                       <span class=" p-float-label mr-3 align-search-items mt-4">
                            <p-inputNumber class="mr-2" mode="decimal" [(ngModel)]="criteria.nombreMoisRetardMax" id="4-2"></p-inputNumber>
                            <label for="4-2">{{'Nombre mois retard' | translate}} Max</label>
                       </span>
                        <span class=" p-float-label mr-3 align-search-items mt-4">
                            <p-inputNumber class="mr-2" mode="decimal" [(ngModel)]="criteria.montantTotalMin" id="5-1"></p-inputNumber>
                            <label for="5-1">{{'Montant total' | translate}} Min</label>
                        </span>
                       <span class=" p-float-label mr-3 align-search-items mt-4">
                            <p-inputNumber class="mr-2" mode="decimal" [(ngModel)]="criteria.montantTotalMax" id="5-2"></p-inputNumber>
                            <label for="5-2">{{'Montant total' | translate}} Max</label>
                       </span>

                        <span class=" p-float-label mr-3 align-search-items mt-4">
                            <p-calendar class="mr-2" [(ngModel)]="criteria.datePresentationFrom"
                                    id="6-1"
                                    dateFormat="dd-MM-yy"></p-calendar>
                            <label for="6-1">{{'Date presentation' | translate}} Min</label>
                        </span>

                         <span class=" p-float-label mr-3 align-search-items mt-4">
                            <p-calendar class="mr-2" [(ngModel)]="criteria.datePresentationTo"
                                    id="6-2"
                                    dateFormat="dd-MM-yy"></p-calendar>
                            <label for="6-2">{{'Date presentation' | translate}} Max</label>
                        </span>


                        <span class=" p-float-label mr-3 align-search-items mt-4">
                            <p-calendar class="mr-2" [(ngModel)]="criteria.dateTaxeTnbFrom"
                                    id="7-1"
                                    dateFormat="dd-MM-yy"></p-calendar>
                            <label for="7-1">{{'Date taxe tnb' | translate}} Min</label>
                        </span>

                         <span class=" p-float-label mr-3 align-search-items mt-4">
                            <p-calendar class="mr-2" [(ngModel)]="criteria.dateTaxeTnbTo"
                                    id="7-2"
                                    dateFormat="dd-MM-yy"></p-calendar>
                            <label for="7-2">{{'Date taxe tnb' | translate}} Max</label>
                        </span>

                        <span class=" p-float-label mr-3 align-search-items mt-4">
                            <p-dropdown [options]="redevables" [(ngModel)]="criteria.redevable" id="8" [filter]="true"
                                        [showClear]="true"  placeholder="{{'Redevable' | translate}}" optionLabel="cin">
                            </p-dropdown>
                        </span>
                        <span class=" p-float-label mr-3 align-search-items mt-4">
                            <p-dropdown [options]="terrains" [(ngModel)]="criteria.terrain" id="9" [filter]="true"
                                        [showClear]="true"  placeholder="{{'Terrain' | translate}}" optionLabel="ref">
                            </p-dropdown>
                        </span>
                        <span class=" p-float-label mr-3 align-search-items mt-4">
                            <p-dropdown [options]="tauxTaxTnbs" [(ngModel)]="criteria.tauxTaxTnb" id="10" [filter]="true"
                                        [showClear]="true"  placeholder="{{'Taux tax tnb' | translate}}" optionLabel="id">
                            </p-dropdown>
                        </span>
                </div>

                <div class="align-search-button">
                    <button pButton pRipple label="{{'validate' | translate}}" icon="pi pi-sort-amount-down" class="p-button-info mr-2" (click)="findPaginatedByCriteria()"></button>
                </div>
            </p-toolbar>


            <p-table #dt [value]="items" [columns]="cols" [rows]="8" [paginator]="false"
                    [globalFilterFields]="['annee', 'montantBase', 'mantantRetard', 'nombreMoisRetard', 'montantTotal', 'datePresentation', 'dateTaxeTnb', 'redevablecin', 'terrainref', 'tauxTaxTnbid']" [(selection)]="selections"
                    [rowHover]="true" dataKey="id" styleClass="p-datatable-customers"
                    currentPageReportTemplate="{{'Les éléments de {first} à {last} sur {totalRecords} ' | translate}}"
                    [showCurrentPageReport]="true" [rowsPerPageOptions]="[10,25,50]" selectionMode="multiple">
                <ng-template pTemplate="caption">
                    <div class="flex flex-column flex-row justify-content-between table-header">
                        <h5 class="p-m-0">{{'taxTnbHeader' | translate}}</h5>
                        <span class="p-input-icon-left ml-auto">
                            <i class="pi pi-search"></i>
                            <input pInputText type="text" placeholder="{{'searchInput' | translate}}" (input)="dt.filterGlobal($event.target.value, 'contains')"/>
                        </span>
                    </div>
                </ng-template>
                <ng-template pTemplate="header">
                    <tr>
                        <th style="width: 3rem">
                            <p-tableHeaderCheckbox></p-tableHeaderCheckbox>
                        </th>
                                
                        <th pSortableColumn="annee">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'Annee' | translate}}</span>
                                <p-sortIcon field="annee"></p-sortIcon>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="montantBase">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'Montant base' | translate}}</span>
                                <p-sortIcon field="montantBase"></p-sortIcon>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="mantantRetard">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'Mantant retard' | translate}}</span>
                                <p-sortIcon field="mantantRetard"></p-sortIcon>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="nombreMoisRetard">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'Nombre mois retard' | translate}}</span>
                                <p-sortIcon field="nombreMoisRetard"></p-sortIcon>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="montantTotal">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'Montant total' | translate}}</span>
                                <p-sortIcon field="montantTotal"></p-sortIcon>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="datePresentation">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'Date presentation' | translate}}</span>
                                <p-sortIcon field="datePresentation"></p-sortIcon>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="dateTaxeTnb">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'Date taxe tnb' | translate}}</span>
                                <p-sortIcon field="dateTaxeTnb"></p-sortIcon>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="redevable">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'Redevable' | translate}}</span>
                                <p-sortIcon field="redevable"></p-sortIcon>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="terrain">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'Terrain' | translate}}</span>
                                <p-sortIcon field="terrain"></p-sortIcon>
                            </div>
                        </th>
                                
                                <!-- 
                        <th pSortableColumn="tauxTaxTnb">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'Taux tax tnb' | translate}}</span>
                                <p-sortIcon field="tauxTaxTnb"></p-sortIcon>
                            </div>
                        </th>
                                --> 
                        <th>Actions</th>
                    </tr>
                </ng-template>
                <ng-template pTemplate="body" let-element>
                    <tr>
                        <td>
                            <p-tableCheckbox [value]="element"></p-tableCheckbox>
                        </td>
                            
                        <td>{{element.annee}}</td>
                            
                            
                        <td>{{element.montantBase}}</td>
                            
                            
                        <td>{{element.mantantRetard}}</td>
                            
                            
                        <td>{{element.nombreMoisRetard}}</td>
                            
                            
                        <td>{{element.montantTotal}}</td>
                            
                            
                        <td>{{element.datePresentation | date :'dd/MM/yyyy HH:mm' }}</td>
                            
                            
                        <td>{{element.dateTaxeTnb | date :'dd/MM/yyyy HH:mm' }}</td>
                            
                            
                        <td>{{element.redevable?.cin}}</td>
                            
                            
                        <td>{{element.terrain?.ref}}</td>
                            
                             <!-- 
                        <td>{{element.tauxTaxTnb?.id}}</td>
                             --> 
                        <td>
                            <button pButton pRipple icon="pi pi-pencil"  class="p-button-rounded p-button-success mr-2" (click)="edit(element)"></button>
                            <button pButton pRipple icon="pi pi-list" class="p-button-rounded p-button-info mr-2" (click)="view(element)"></button>
                            <button pButton pRipple icon="pi pi-trash" class="p-button-rounded p-button-danger mr-2" (click)="delete(element)"></button>
                            <button pButton pRipple icon="pi pi-copy" class="p-button-rounded p-button-raised p-button-warning mr-2" (click)="duplicate(element)"></button>
                        </td>
                    </tr>
                </ng-template>

                <ng-template pTemplate="summary">
                    <p-paginator  [rows]="10" [totalRecords]="totalRecords" (onPageChange)="onPage($event)"></p-paginator>
                    <div class="p-d-flex p-ai-center p-jc-between">
                        En totale il {{items ? totalRecords == 1 ? 'y a' : 'y a' : 'y a' }} {{items ? totalRecords : 0 }} {{items ? totalRecords == 1 ? 'tax tnb' : 'tax tnbs' : 0 }}.
                    </div>
                </ng-template>
            </p-table>
        </div>

        <app-tax-tnb-create-admin></app-tax-tnb-create-admin>
        <app-tax-tnb-edit-admin></app-tax-tnb-edit-admin>
        <app-tax-tnb-view-admin></app-tax-tnb-view-admin>
        <p-confirmDialog [style]="{width: '450px'}"></p-confirmDialog>
    </div>
</div>
